import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { ELECTRIC_DRYER_COMPLAINT_CHIPS } from './electricDryerComplaints';
import { electricDryerRoutingConfig } from './electricDryerRouting';

export const electricDryerWizard: WizardDefinition = {
  applianceType: 'electric_dryer',
  templateId: 'electric_dryer',
  title: 'Electric Dryer Diagnostic',
  icon: 'electric_dryer',
  estimatedCompletionMinutes: 16,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: ELECTRIC_DRYER_COMPLAINT_CHIPS,
  routing: electricDryerRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'vent', 'lint', 'airflow'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'vent', 'lint', 'drum'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'heat', 'airflow', 'drum'],
    },
    {
      sectionId: 'heat_circuit',
      stepKey: 'heat',
      title: 'Heat Circuit Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['heat', 'element', 'fuse', 'thermostat'],
    },
    {
      sectionId: 'motor_electrical',
      stepKey: 'motor',
      title: 'Motor & Electrical Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['motor', 'voltage', 'belt', 'board'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
