import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { GAS_RANGE_COMPLAINT_CHIPS } from './gasRangeComplaints';
import { gasRangeRoutingConfig } from './gasRangeRouting';

export const gasRangeWizard: WizardDefinition = {
  applianceType: 'gas_range',
  templateId: 'gas_range',
  title: 'Gas Range Diagnostic',
  icon: 'gas_range',
  estimatedCompletionMinutes: 18,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: GAS_RANGE_COMPLAINT_CHIPS,
  routing: gasRangeRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Commonly Missed Items',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'gas', 'ventilation', 'lp'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Customer Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'igniter', 'burner', 'valve'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'ignition', 'burners'],
    },
    {
      sectionId: 'electrical_at_board',
      stepKey: 'electrical',
      title: 'Electrical at Board / Valve',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['voltage', 'igniter', 'valve', 'electrical'],
    },
    {
      sectionId: 'gas_flame_readings',
      stepKey: 'flame',
      title: 'Gas / Flame Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['gas', 'flame', 'pressure'],
    },
    {
      sectionId: 'board_readings',
      stepKey: 'board',
      title: 'Control Board Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['board', 'voltage', 'valve'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
