#!/usr/bin/env python3
"""Generate TypeScript imports for all procedure seed JSON under procedures/seed/."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEED_DIR = ROOT / "frontend" / "components" / "diagnostics" / "procedures" / "seed"
OUT_FILE = (
    ROOT
    / "frontend"
    / "components"
    / "diagnostics"
    / "procedures"
    / "procedureRegistry.generated.ts"
)

HEADER = """// AUTO-GENERATED by backend/scripts/generate_procedure_registry.py — do not edit.
// Re-run after adding or removing procedure seed JSON files.

"""


def import_symbol(relative_path: Path) -> str:
    stem = "_".join(relative_path.with_suffix("").parts)
    stem = re.sub(r"[^a-zA-Z0-9_]", "_", stem)
    stem = re.sub(r"_+", "_", stem).strip("_")
    if not stem or stem[0].isdigit():
        stem = f"seed_{stem}"
    return stem


def posix_import_path(relative_path: Path) -> str:
    return "./seed/" + relative_path.as_posix()


def is_bundle(path: Path) -> bool:
    return "bundles" in path.parts


def is_procedure_seed(path: Path) -> bool:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return False
    return isinstance(data, dict) and "entryStepId" in data and "platformId" in data


def main() -> int:
    if not SEED_DIR.is_dir():
        print(f"Seed directory not found: {SEED_DIR}", file=sys.stderr)
        return 1

    seed_files = sorted(SEED_DIR.rglob("*.json"))
    bundle_files = [path for path in seed_files if is_bundle(path.relative_to(SEED_DIR))]
    procedure_files = [
        path
        for path in seed_files
        if not is_bundle(path.relative_to(SEED_DIR)) and is_procedure_seed(path)
    ]

    lines = [HEADER]
    bundle_symbols: list[str] = []
    procedure_symbols: list[str] = []

    for path in bundle_files:
        rel = path.relative_to(SEED_DIR)
        symbol = import_symbol(rel)
        lines.append(f"import {symbol} from '{posix_import_path(rel)}';")
        bundle_symbols.append(symbol)

    lines.append("")
    for path in procedure_files:
        rel = path.relative_to(SEED_DIR)
        symbol = import_symbol(rel)
        lines.append(f"import {symbol} from '{posix_import_path(rel)}';")
        procedure_symbols.append(symbol)

    lines.append("")
    lines.append("import type { ServiceModeBundle, ServiceProcedureSeed } from './types';")
    lines.append("")
    lines.append(
        "export const GENERATED_SERVICE_MODE_BUNDLES: ServiceModeBundle[] = ["
    )
    for symbol in bundle_symbols:
        lines.append(f"  {symbol} as ServiceModeBundle,")
    lines.append("];")
    lines.append("")
    lines.append(
        "export const GENERATED_PROCEDURE_SEEDS: ServiceProcedureSeed[] = ["
    )
    for symbol in procedure_symbols:
        lines.append(f"  {symbol} as ServiceProcedureSeed,")
    lines.append("];")
    lines.append("")

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Wrote {OUT_FILE.relative_to(ROOT)} "
        f"({len(procedure_symbols)} procedures, {len(bundle_symbols)} bundles)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
