import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { DISHWASHER_COMPLAINT_CHIPS } from './dishwasherComplaints';
import { dishwasherRoutingConfig } from './dishwasherRouting';

export const dishwasherWizard: WizardDefinition = {
  applianceType: 'dishwasher',
  templateId: 'dishwasher',
  title: 'Dishwasher Diagnostic',
  icon: 'dishwasher',
  estimatedCompletionMinutes: 14,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: DISHWASHER_COMPLAINT_CHIPS,
  routing: dishwasherRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'drain', 'detergent', 'installation'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'spray', 'filter', 'drain', 'leak'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'fill', 'wash', 'drain', 'dry'],
    },
    {
      sectionId: 'heat_water',
      stepKey: 'heat',
      title: 'Heat & Water Readings',
      estimatedMinutes: 2,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['heat', 'temperature', 'heater', 'thermistor'],
    },
    {
      sectionId: 'motor_electrical',
      stepKey: 'motor',
      title: 'Motor & Electrical Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['motor', 'voltage', 'pump', 'valve', 'board'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
