import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { STANDALONE_FREEZER_COMPLAINT_CHIPS } from './standaloneFreezerComplaints';
import { standaloneFreezerRoutingConfig } from './standaloneFreezerRouting';

export const standaloneFreezerWizard: WizardDefinition = {
  applianceType: 'freezer',
  templateId: 'standalone_freezer',
  title: 'Standalone Freezer Diagnostic',
  icon: 'freezer',
  estimatedCompletionMinutes: 18,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: STANDALONE_FREEZER_COMPLAINT_CHIPS,
  routing: standaloneFreezerRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'door', 'condenser', 'drain'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'duration'],
    },
    {
      sectionId: 'temperature_checks',
      stepKey: 'temperature',
      title: 'Temperature Checks',
      estimatedMinutes: 2,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['temperature', 'cabinet', 'ambient'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'gasket', 'frost', 'condenser', 'drain'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'compressor', 'fans', 'defrost'],
    },
    {
      sectionId: 'compressor_sealed_system',
      stepKey: 'sealedSystem',
      title: 'Compressor & Sealed System Readings',
      estimatedMinutes: 4,
      weight: 14,
      optional: true,
      canSkip: true,
      collects: ['amps', 'voltage', 'resistance', 'compressor', 'refrigerant'],
    },
    {
      sectionId: 'defrost_circuit',
      stepKey: 'defrost',
      title: 'Defrost Circuit Readings',
      estimatedMinutes: 2,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['defrost', 'resistance', 'thermistor'],
    },
    {
      sectionId: 'fans_and_electrical',
      stepKey: 'fans',
      title: 'Fans & Electrical Readings',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['fans', 'amps', 'voltage'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
