import type { ProcedureImage } from './types';

const ASSET_BASE = '/images/procedures/whirlpool_fl_dd';

/** Cropped OEM figures for W11169652 — generated by crop_w11169652_procedure_figures.py */
export const W11169652_DIAGRAMS: Record<string, ProcedureImage> = {
  'w11169652-rfi-filter-figure1': {
    id: 'w11169652-rfi-filter-figure1',
    caption: 'RFI filter — line in/out (Figure 1, manual p. 3-6)',
    assetPath: `${ASSET_BASE}/w11169652-rfi-filter-figure1.png`,
  },
  'w11169652-acu-pinout-figure2': {
    id: 'w11169652-acu-pinout-figure2',
    caption: 'ACU connectors & pinouts (Figure 2, manual p. 3-7)',
    assetPath: `${ASSET_BASE}/w11169652-acu-pinout-figure2.png`,
  },
  'w11169652-motor-j6-location': {
    id: 'w11169652-motor-j6-location',
    caption: 'Motor harness connector J6 on ACU (TEST #3)',
    assetPath: `${ASSET_BASE}/w11169652-motor-j6-location.png`,
  },
  'w11169652-drum-light-j16-location': {
    id: 'w11169652-drum-light-j16-location',
    caption: 'Drum light connector J16 on ACU (TEST #5)',
    assetPath: `${ASSET_BASE}/w11169652-drum-light-j16-location.png`,
  },
  'w11169652-inlet-valves-strip': {
    id: 'w11169652-inlet-valves-strip',
    caption: 'Inlet water valve strip circuit — J8 (TEST #6)',
    assetPath: `${ASSET_BASE}/w11169652-inlet-valves-strip.png`,
  },
  'w11169652-water-level-j14': {
    id: 'w11169652-water-level-j14',
    caption: 'Water level sensor / APS — J14 (TEST #7)',
    assetPath: `${ASSET_BASE}/w11169652-water-level-j14.png`,
  },
  'w11169652-wash-heater-j3-location': {
    id: 'w11169652-wash-heater-j3-location',
    caption: 'Wash heater & temperature sensor — J3 / J15 (TEST #9–10)',
    assetPath: `${ASSET_BASE}/w11169652-wash-heater-j3-location.png`,
  },
  'w11169652-dosing-pump-strip': {
    id: 'w11169652-dosing-pump-strip',
    caption: 'Detergent dosing pump strip circuit — J10 (TEST #11B)',
    assetPath: `${ASSET_BASE}/w11169652-dosing-pump-strip.png`,
  },
  'w11169652-bulk-level-strip': {
    id: 'w11169652-bulk-level-strip',
    caption: 'Bulk dispenser level sensing — J17 (TEST #12B)',
    assetPath: `${ASSET_BASE}/w11169652-bulk-level-strip.png`,
  },
  'w11169652-vent-fan-j12-strip': {
    id: 'w11169652-vent-fan-j12-strip',
    caption: 'Vent fan / blower strip circuit — J12 (TEST #13 / #17)',
    assetPath: `${ASSET_BASE}/w11169652-vent-fan-j12-strip.png`,
  },
  'w11169652-baffle-j9-location': {
    id: 'w11169652-baffle-j9-location',
    caption: 'Vent baffle solenoid — J9 (TEST #14)',
    assetPath: `${ASSET_BASE}/w11169652-baffle-j9-location.png`,
  },
  'w11169652-dry-heater-j4-location': {
    id: 'w11169652-dry-heater-j4-location',
    caption: 'Dry heating element — J4 (TEST #15)',
    assetPath: `${ASSET_BASE}/w11169652-dry-heater-j4-location.png`,
  },
  'w11169652-dry-ntc-j13-location': {
    id: 'w11169652-dry-ntc-j13-location',
    caption: 'Dry temperature sensor NTC — J13 (TEST #16)',
    assetPath: `${ASSET_BASE}/w11169652-dry-ntc-j13-location.png`,
  },
};

/** Diagram ids to attach for a measurement test-point connector label. */
const CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  RFI: ['w11169652-rfi-filter-figure1'],
  J2: ['w11169652-acu-pinout-figure2'],
  J3: ['w11169652-wash-heater-j3-location', 'w11169652-acu-pinout-figure2'],
  J4: ['w11169652-dry-heater-j4-location', 'w11169652-acu-pinout-figure2'],
  J6: ['w11169652-motor-j6-location', 'w11169652-acu-pinout-figure2'],
  J7: ['w11169652-acu-pinout-figure2'],
  J8: ['w11169652-inlet-valves-strip', 'w11169652-acu-pinout-figure2'],
  J9: ['w11169652-baffle-j9-location', 'w11169652-acu-pinout-figure2'],
  J10: ['w11169652-dosing-pump-strip', 'w11169652-acu-pinout-figure2'],
  J11: ['w11169652-acu-pinout-figure2'],
  J12: ['w11169652-vent-fan-j12-strip', 'w11169652-acu-pinout-figure2'],
  J13: ['w11169652-dry-ntc-j13-location', 'w11169652-acu-pinout-figure2'],
  J14: ['w11169652-water-level-j14', 'w11169652-acu-pinout-figure2'],
  J15: ['w11169652-wash-heater-j3-location', 'w11169652-acu-pinout-figure2'],
  J16: ['w11169652-drum-light-j16-location', 'w11169652-acu-pinout-figure2'],
  J17: ['w11169652-bulk-level-strip', 'w11169652-acu-pinout-figure2'],
  J19: ['w11169652-acu-pinout-figure2'],
  Pump: ['w11169652-dosing-pump-strip'],
  'Vent fan': ['w11169652-vent-fan-j12-strip'],
  Blower: ['w11169652-vent-fan-j12-strip'],
  'Dry NTC': ['w11169652-dry-ntc-j13-location'],
  'Wash NTC': ['w11169652-wash-heater-j3-location'],
  'Level SW': ['w11169652-bulk-level-strip'],
};

export function resolveDiagramsForConnector(connector: string): ProcedureImage[] {
  const ids = CONNECTOR_DIAGRAM_IDS[connector] || [];
  return ids
    .map((id) => W11169652_DIAGRAMS[id])
    .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
}

export function serializeProcedureImages(images: ProcedureImage[]): ProcedureImage[] {
  return images.map(({ id, caption, assetPath }) => ({ id, caption, assetPath }));
}
