// AUTO-GENERATED by backend/scripts/generate_procedure_registry.py — do not edit.
// Re-run after adding or removing procedure seed JSON files.


import whirlpool_acu_tl_dryer_bundles_w11416805_diagnostic_entry from './seed/whirlpool_acu_tl_dryer/bundles/w11416805-diagnostic-entry.json';
import whirlpool_ccu_dryer_bundles_w10680150_diagnostic_entry from './seed/whirlpool_ccu_dryer/bundles/w10680150-diagnostic-entry.json';
import whirlpool_dishwasher_acu_bundles_w11633848_service_diagnostic_entry from './seed/whirlpool_dishwasher_acu/bundles/w11633848-service-diagnostic-entry.json';
import whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry from './seed/whirlpool_duet_sport/bundles/w8178558-diagnostic-history-entry.json';
import whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test from './seed/whirlpool_duet_sport/bundles/w8178558-manual-diagnostic-test.json';
import whirlpool_duet_sport_dryer_bundles_w8178559_diagnostic_entry from './seed/whirlpool_duet_sport_dryer/bundles/w8178559-diagnostic-entry.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-dry-blower.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-vent-fan.json';
import whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump from './seed/whirlpool_fl_dd/bundles/w11169652-load-test-detergent-pump.json';
import whirlpool_fl_dd_bundles_w11169652_quick_service_cycle from './seed/whirlpool_fl_dd/bundles/w11169652-quick-service-cycle.json';
import whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry from './seed/whirlpool_fl_dd/bundles/w11169652-service-diagnostic-entry.json';
import whirlpool_fl_dd_bundles_w11169652_service_mode from './seed/whirlpool_fl_dd/bundles/w11169652-service-mode.json';
import whirlpool_tl_dd_bundles_w10864849_service_diagnostic_entry from './seed/whirlpool_tl_dd/bundles/w10864849-service-diagnostic-entry.json';
import whirlpool_tl_dd_bundles_w10864849_service_test_mode from './seed/whirlpool_tl_dd/bundles/w10864849-service-test-mode.json';

import whirlpool_acu_tl_dryer_w11416805_acu_power from './seed/whirlpool_acu_tl_dryer/w11416805-acu-power.json';
import whirlpool_acu_tl_dryer_w11416805_door_switch from './seed/whirlpool_acu_tl_dryer/w11416805-door-switch.json';
import whirlpool_acu_tl_dryer_w11416805_drum_light from './seed/whirlpool_acu_tl_dryer/w11416805-drum-light.json';
import whirlpool_acu_tl_dryer_w11416805_gas_valve from './seed/whirlpool_acu_tl_dryer/w11416805-gas-valve.json';
import whirlpool_acu_tl_dryer_w11416805_heater_electric from './seed/whirlpool_acu_tl_dryer/w11416805-heater-electric.json';
import whirlpool_acu_tl_dryer_w11416805_heater_gas from './seed/whirlpool_acu_tl_dryer/w11416805-heater-gas.json';
import whirlpool_acu_tl_dryer_w11416805_hmi from './seed/whirlpool_acu_tl_dryer/w11416805-hmi.json';
import whirlpool_acu_tl_dryer_w11416805_moisture_sensor from './seed/whirlpool_acu_tl_dryer/w11416805-moisture-sensor.json';
import whirlpool_acu_tl_dryer_w11416805_motor_circuit from './seed/whirlpool_acu_tl_dryer/w11416805-motor-circuit.json';
import whirlpool_acu_tl_dryer_w11416805_supply_connections from './seed/whirlpool_acu_tl_dryer/w11416805-supply-connections.json';
import whirlpool_acu_tl_dryer_w11416805_thermal_cutoff from './seed/whirlpool_acu_tl_dryer/w11416805-thermal-cutoff.json';
import whirlpool_acu_tl_dryer_w11416805_thermal_fuse from './seed/whirlpool_acu_tl_dryer/w11416805-thermal-fuse.json';
import whirlpool_acu_tl_dryer_w11416805_thermistors from './seed/whirlpool_acu_tl_dryer/w11416805-thermistors.json';
import whirlpool_acu_tl_dryer_w11416805_water_valve from './seed/whirlpool_acu_tl_dryer/w11416805-water-valve.json';
import whirlpool_ccu_dryer_w10680150_button_indicator from './seed/whirlpool_ccu_dryer/w10680150-button-indicator.json';
import whirlpool_ccu_dryer_w10680150_ccu_power from './seed/whirlpool_ccu_dryer/w10680150-ccu-power.json';
import whirlpool_ccu_dryer_w10680150_door_switch from './seed/whirlpool_ccu_dryer/w10680150-door-switch.json';
import whirlpool_ccu_dryer_w10680150_dryness_adjust from './seed/whirlpool_ccu_dryer/w10680150-dryness-adjust.json';
import whirlpool_ccu_dryer_w10680150_gas_valve from './seed/whirlpool_ccu_dryer/w10680150-gas-valve.json';
import whirlpool_ccu_dryer_w10680150_heater_electric from './seed/whirlpool_ccu_dryer/w10680150-heater-electric.json';
import whirlpool_ccu_dryer_w10680150_heater_gas from './seed/whirlpool_ccu_dryer/w10680150-heater-gas.json';
import whirlpool_ccu_dryer_w10680150_moisture_sensor from './seed/whirlpool_ccu_dryer/w10680150-moisture-sensor.json';
import whirlpool_ccu_dryer_w10680150_motor_circuit from './seed/whirlpool_ccu_dryer/w10680150-motor-circuit.json';
import whirlpool_ccu_dryer_w10680150_supply_connections from './seed/whirlpool_ccu_dryer/w10680150-supply-connections.json';
import whirlpool_ccu_dryer_w10680150_thermal_cutoff from './seed/whirlpool_ccu_dryer/w10680150-thermal-cutoff.json';
import whirlpool_ccu_dryer_w10680150_thermal_fuse from './seed/whirlpool_ccu_dryer/w10680150-thermal-fuse.json';
import whirlpool_ccu_dryer_w10680150_thermistors from './seed/whirlpool_ccu_dryer/w10680150-thermistors.json';
import whirlpool_dishwasher_acu_w11633848_acu_power from './seed/whirlpool_dishwasher_acu/w11633848-acu-power.json';
import whirlpool_dishwasher_acu_w11633848_dc_fan from './seed/whirlpool_dishwasher_acu/w11633848-dc-fan.json';
import whirlpool_dishwasher_acu_w11633848_dispenser from './seed/whirlpool_dishwasher_acu/w11633848-dispenser.json';
import whirlpool_dishwasher_acu_w11633848_diverter_motor from './seed/whirlpool_dishwasher_acu/w11633848-diverter-motor.json';
import whirlpool_dishwasher_acu_w11633848_diverter_sensor from './seed/whirlpool_dishwasher_acu/w11633848-diverter-sensor.json';
import whirlpool_dishwasher_acu_w11633848_door_switch from './seed/whirlpool_dishwasher_acu/w11633848-door-switch.json';
import whirlpool_dishwasher_acu_w11633848_drain_motor from './seed/whirlpool_dishwasher_acu/w11633848-drain-motor.json';
import whirlpool_dishwasher_acu_w11633848_fill_valve from './seed/whirlpool_dishwasher_acu/w11633848-fill-valve.json';
import whirlpool_dishwasher_acu_w11633848_heater from './seed/whirlpool_dishwasher_acu/w11633848-heater.json';
import whirlpool_dishwasher_acu_w11633848_overfill_switch from './seed/whirlpool_dishwasher_acu/w11633848-overfill-switch.json';
import whirlpool_dishwasher_acu_w11633848_owi_sensor from './seed/whirlpool_dishwasher_acu/w11633848-owi-sensor.json';
import whirlpool_dishwasher_acu_w11633848_triac_fuse from './seed/whirlpool_dishwasher_acu/w11633848-triac-fuse.json';
import whirlpool_dishwasher_acu_w11633848_wash_motor from './seed/whirlpool_dishwasher_acu/w11633848-wash-motor.json';
import whirlpool_duet_sport_w8178558_dispenser_motor from './seed/whirlpool_duet_sport/w8178558-dispenser-motor.json';
import whirlpool_duet_sport_w8178558_door_lock from './seed/whirlpool_duet_sport/w8178558-door-lock.json';
import whirlpool_duet_sport_w8178558_drain_pump from './seed/whirlpool_duet_sport/w8178558-drain-pump.json';
import whirlpool_duet_sport_w8178558_inlet_valves from './seed/whirlpool_duet_sport/w8178558-inlet-valves.json';
import whirlpool_duet_sport_w8178558_interlock_switch from './seed/whirlpool_duet_sport/w8178558-interlock-switch.json';
import whirlpool_duet_sport_w8178558_motor_circuit from './seed/whirlpool_duet_sport/w8178558-motor-circuit.json';
import whirlpool_duet_sport_w8178558_pressure_switch from './seed/whirlpool_duet_sport/w8178558-pressure-switch.json';
import whirlpool_duet_sport_w8178558_wash_heater from './seed/whirlpool_duet_sport/w8178558-wash-heater.json';
import whirlpool_duet_sport_w8178558_wash_ntc from './seed/whirlpool_duet_sport/w8178558-wash-ntc.json';
import whirlpool_duet_sport_dryer_w8178559_button_indicator from './seed/whirlpool_duet_sport_dryer/w8178559-button-indicator.json';
import whirlpool_duet_sport_dryer_w8178559_door_switch from './seed/whirlpool_duet_sport_dryer/w8178559-door-switch.json';
import whirlpool_duet_sport_dryer_w8178559_dryness_adjust from './seed/whirlpool_duet_sport_dryer/w8178559-dryness-adjust.json';
import whirlpool_duet_sport_dryer_w8178559_exhaust_thermistor from './seed/whirlpool_duet_sport_dryer/w8178559-exhaust-thermistor.json';
import whirlpool_duet_sport_dryer_w8178559_gas_ignitor from './seed/whirlpool_duet_sport_dryer/w8178559-gas-ignitor.json';
import whirlpool_duet_sport_dryer_w8178559_gas_valve from './seed/whirlpool_duet_sport_dryer/w8178559-gas-valve.json';
import whirlpool_duet_sport_dryer_w8178559_heater_electric from './seed/whirlpool_duet_sport_dryer/w8178559-heater-electric.json';
import whirlpool_duet_sport_dryer_w8178559_heater_gas from './seed/whirlpool_duet_sport_dryer/w8178559-heater-gas.json';
import whirlpool_duet_sport_dryer_w8178559_moisture_sensor from './seed/whirlpool_duet_sport_dryer/w8178559-moisture-sensor.json';
import whirlpool_duet_sport_dryer_w8178559_motor_circuit from './seed/whirlpool_duet_sport_dryer/w8178559-motor-circuit.json';
import whirlpool_duet_sport_dryer_w8178559_supply_connections from './seed/whirlpool_duet_sport_dryer/w8178559-supply-connections.json';
import whirlpool_duet_sport_dryer_w8178559_thermal_cutoff from './seed/whirlpool_duet_sport_dryer/w8178559-thermal-cutoff.json';
import whirlpool_duet_sport_dryer_w8178559_thermal_fuse from './seed/whirlpool_duet_sport_dryer/w8178559-thermal-fuse.json';
import whirlpool_fl_dd_w11169652_test_01_acu_power from './seed/whirlpool_fl_dd/w11169652-test-01-acu-power.json';
import whirlpool_fl_dd_w11169652_test_02_hmi from './seed/whirlpool_fl_dd/w11169652-test-02-hmi.json';
import whirlpool_fl_dd_w11169652_test_03_motor from './seed/whirlpool_fl_dd/w11169652-test-03-motor.json';
import whirlpool_fl_dd_w11169652_test_04_door_lock from './seed/whirlpool_fl_dd/w11169652-test-04-door-lock.json';
import whirlpool_fl_dd_w11169652_test_05_drum_light from './seed/whirlpool_fl_dd/w11169652-test-05-drum-light.json';
import whirlpool_fl_dd_w11169652_test_06_inlet_valves from './seed/whirlpool_fl_dd/w11169652-test-06-inlet-valves.json';
import whirlpool_fl_dd_w11169652_test_07_water_level_sensor from './seed/whirlpool_fl_dd/w11169652-test-07-water-level-sensor.json';
import whirlpool_fl_dd_w11169652_test_08_drain_pump from './seed/whirlpool_fl_dd/w11169652-test-08-drain-pump.json';
import whirlpool_fl_dd_w11169652_test_09_wash_heater from './seed/whirlpool_fl_dd/w11169652-test-09-wash-heater.json';
import whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-10-wash-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser from './seed/whirlpool_fl_dd/w11169652-test-11a-single-dose-dispenser.json';
import whirlpool_fl_dd_w11169652_test_11b_dosing_pump from './seed/whirlpool_fl_dd/w11169652-test-11b-dosing-pump.json';
import whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser from './seed/whirlpool_fl_dd/w11169652-test-12a-bulk-dispenser.json';
import whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing from './seed/whirlpool_fl_dd/w11169652-test-12b-bulk-level-sensing.json';
import whirlpool_fl_dd_w11169652_test_13_vent_fan from './seed/whirlpool_fl_dd/w11169652-test-13-vent-fan.json';
import whirlpool_fl_dd_w11169652_test_14_vent_baffle from './seed/whirlpool_fl_dd/w11169652-test-14-vent-baffle.json';
import whirlpool_fl_dd_w11169652_test_15_dry_heater from './seed/whirlpool_fl_dd/w11169652-test-15-dry-heater.json';
import whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-16-dry-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_17_dry_blower from './seed/whirlpool_fl_dd/w11169652-test-17-dry-blower.json';
import whirlpool_tl_dd_w10864849_test_01_acu_power from './seed/whirlpool_tl_dd/w10864849-test-01-acu-power.json';
import whirlpool_tl_dd_w10864849_test_02_valves from './seed/whirlpool_tl_dd/w10864849-test-02-valves.json';
import whirlpool_tl_dd_w10864849_test_03_drive_system from './seed/whirlpool_tl_dd/w10864849-test-03-drive-system.json';
import whirlpool_tl_dd_w10864849_test_03a_shifter from './seed/whirlpool_tl_dd/w10864849-test-03a-shifter.json';
import whirlpool_tl_dd_w10864849_test_03b_motor from './seed/whirlpool_tl_dd/w10864849-test-03b-motor.json';
import whirlpool_tl_dd_w10864849_test_04_keys_encoders from './seed/whirlpool_tl_dd/w10864849-test-04-keys-encoders.json';
import whirlpool_tl_dd_w10864849_test_05_temp_thermistor from './seed/whirlpool_tl_dd/w10864849-test-05-temp-thermistor.json';
import whirlpool_tl_dd_w10864849_test_06_water_level from './seed/whirlpool_tl_dd/w10864849-test-06-water-level.json';
import whirlpool_tl_dd_w10864849_test_07_drain_recirc_pump from './seed/whirlpool_tl_dd/w10864849-test-07-drain-recirc-pump.json';
import whirlpool_tl_dd_w10864849_test_08_lid_lock from './seed/whirlpool_tl_dd/w10864849-test-08-lid-lock.json';
import whirlpool_tl_dd_w10864849_test_09_heater from './seed/whirlpool_tl_dd/w10864849-test-09-heater.json';
import whirlpool_tl_dd_w10864849_test_10_service_leds from './seed/whirlpool_tl_dd/w10864849-test-10-service-leds.json';
import whirlpool_tl_dd_w10864849_test_11_basket_light from './seed/whirlpool_tl_dd/w10864849-test-11-basket-light.json';
import whirlpool_tl_dd_w10864849_test_12_bulk_dispense from './seed/whirlpool_tl_dd/w10864849-test-12-bulk-dispense.json';

import type { ServiceModeBundle, ServiceProcedureSeed } from './types';

export const GENERATED_SERVICE_MODE_BUNDLES: ServiceModeBundle[] = [
  whirlpool_acu_tl_dryer_bundles_w11416805_diagnostic_entry as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w10680150_diagnostic_entry as ServiceModeBundle,
  whirlpool_dishwasher_acu_bundles_w11633848_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry as ServiceModeBundle,
  whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test as ServiceModeBundle,
  whirlpool_duet_sport_dryer_bundles_w8178559_diagnostic_entry as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_quick_service_cycle as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_mode as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w10864849_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w10864849_service_test_mode as ServiceModeBundle,
];

export const GENERATED_PROCEDURE_SEEDS: ServiceProcedureSeed[] = [
  whirlpool_acu_tl_dryer_w11416805_acu_power as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_door_switch as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_drum_light as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_gas_valve as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_heater_electric as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_heater_gas as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_hmi as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_moisture_sensor as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_motor_circuit as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_supply_connections as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermal_fuse as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermistors as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_water_valve as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_button_indicator as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_ccu_power as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_door_switch as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_dryness_adjust as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_gas_valve as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_heater_electric as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_heater_gas as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_moisture_sensor as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_motor_circuit as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_supply_connections as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermal_fuse as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermistors as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_acu_power as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_dc_fan as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_dispenser as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_diverter_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_diverter_sensor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_door_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_drain_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_fill_valve as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_heater as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_overfill_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_owi_sensor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_triac_fuse as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_wash_motor as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_dispenser_motor as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_door_lock as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_drain_pump as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_inlet_valves as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_interlock_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_motor_circuit as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_pressure_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_heater as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_ntc as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_button_indicator as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_door_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_dryness_adjust as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_exhaust_thermistor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_gas_ignitor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_gas_valve as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_heater_electric as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_heater_gas as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_moisture_sensor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_motor_circuit as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_supply_connections as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_thermal_fuse as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_02_hmi as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_03_motor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_04_door_lock as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_05_drum_light as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_06_inlet_valves as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_07_water_level_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_08_drain_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_09_wash_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11b_dosing_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_13_vent_fan as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_14_vent_baffle as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_15_dry_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_17_dry_blower as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_04_keys_encoders as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_05_temp_thermistor as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_06_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_07_drain_recirc_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_08_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_09_heater as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_10_service_leds as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_11_basket_light as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_12_bulk_dispense as ServiceProcedureSeed,
];
