// AUTO-GENERATED by backend/scripts/generate_procedure_registry.py — do not edit.
// Re-run after adding or removing procedure seed JSON files.


import whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry from './seed/whirlpool_duet_sport/bundles/w8178558-diagnostic-history-entry.json';
import whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test from './seed/whirlpool_duet_sport/bundles/w8178558-manual-diagnostic-test.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-dry-blower.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-vent-fan.json';
import whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump from './seed/whirlpool_fl_dd/bundles/w11169652-load-test-detergent-pump.json';
import whirlpool_fl_dd_bundles_w11169652_quick_service_cycle from './seed/whirlpool_fl_dd/bundles/w11169652-quick-service-cycle.json';
import whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry from './seed/whirlpool_fl_dd/bundles/w11169652-service-diagnostic-entry.json';
import whirlpool_fl_dd_bundles_w11169652_service_mode from './seed/whirlpool_fl_dd/bundles/w11169652-service-mode.json';

import whirlpool_duet_sport_w8178558_dispenser_motor from './seed/whirlpool_duet_sport/w8178558-dispenser-motor.json';
import whirlpool_duet_sport_w8178558_door_lock from './seed/whirlpool_duet_sport/w8178558-door-lock.json';
import whirlpool_duet_sport_w8178558_drain_pump from './seed/whirlpool_duet_sport/w8178558-drain-pump.json';
import whirlpool_duet_sport_w8178558_inlet_valves from './seed/whirlpool_duet_sport/w8178558-inlet-valves.json';
import whirlpool_duet_sport_w8178558_interlock_switch from './seed/whirlpool_duet_sport/w8178558-interlock-switch.json';
import whirlpool_duet_sport_w8178558_motor_circuit from './seed/whirlpool_duet_sport/w8178558-motor-circuit.json';
import whirlpool_duet_sport_w8178558_pressure_switch from './seed/whirlpool_duet_sport/w8178558-pressure-switch.json';
import whirlpool_duet_sport_w8178558_wash_heater from './seed/whirlpool_duet_sport/w8178558-wash-heater.json';
import whirlpool_duet_sport_w8178558_wash_ntc from './seed/whirlpool_duet_sport/w8178558-wash-ntc.json';
import whirlpool_fl_dd_w11169652_test_01_acu_power from './seed/whirlpool_fl_dd/w11169652-test-01-acu-power.json';
import whirlpool_fl_dd_w11169652_test_02_hmi from './seed/whirlpool_fl_dd/w11169652-test-02-hmi.json';
import whirlpool_fl_dd_w11169652_test_03_motor from './seed/whirlpool_fl_dd/w11169652-test-03-motor.json';
import whirlpool_fl_dd_w11169652_test_04_door_lock from './seed/whirlpool_fl_dd/w11169652-test-04-door-lock.json';
import whirlpool_fl_dd_w11169652_test_05_drum_light from './seed/whirlpool_fl_dd/w11169652-test-05-drum-light.json';
import whirlpool_fl_dd_w11169652_test_06_inlet_valves from './seed/whirlpool_fl_dd/w11169652-test-06-inlet-valves.json';
import whirlpool_fl_dd_w11169652_test_07_water_level_sensor from './seed/whirlpool_fl_dd/w11169652-test-07-water-level-sensor.json';
import whirlpool_fl_dd_w11169652_test_08_drain_pump from './seed/whirlpool_fl_dd/w11169652-test-08-drain-pump.json';
import whirlpool_fl_dd_w11169652_test_09_wash_heater from './seed/whirlpool_fl_dd/w11169652-test-09-wash-heater.json';
import whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-10-wash-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser from './seed/whirlpool_fl_dd/w11169652-test-11a-single-dose-dispenser.json';
import whirlpool_fl_dd_w11169652_test_11b_dosing_pump from './seed/whirlpool_fl_dd/w11169652-test-11b-dosing-pump.json';
import whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser from './seed/whirlpool_fl_dd/w11169652-test-12a-bulk-dispenser.json';
import whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing from './seed/whirlpool_fl_dd/w11169652-test-12b-bulk-level-sensing.json';
import whirlpool_fl_dd_w11169652_test_13_vent_fan from './seed/whirlpool_fl_dd/w11169652-test-13-vent-fan.json';
import whirlpool_fl_dd_w11169652_test_14_vent_baffle from './seed/whirlpool_fl_dd/w11169652-test-14-vent-baffle.json';
import whirlpool_fl_dd_w11169652_test_15_dry_heater from './seed/whirlpool_fl_dd/w11169652-test-15-dry-heater.json';
import whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-16-dry-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_17_dry_blower from './seed/whirlpool_fl_dd/w11169652-test-17-dry-blower.json';

import type { ServiceModeBundle, ServiceProcedureSeed } from './types';

export const GENERATED_SERVICE_MODE_BUNDLES: ServiceModeBundle[] = [
  whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry as ServiceModeBundle,
  whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_quick_service_cycle as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_mode as ServiceModeBundle,
];

export const GENERATED_PROCEDURE_SEEDS: ServiceProcedureSeed[] = [
  whirlpool_duet_sport_w8178558_dispenser_motor as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_door_lock as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_drain_pump as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_inlet_valves as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_interlock_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_motor_circuit as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_pressure_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_heater as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_ntc as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_02_hmi as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_03_motor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_04_door_lock as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_05_drum_light as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_06_inlet_valves as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_07_water_level_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_08_drain_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_09_wash_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11b_dosing_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_13_vent_fan as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_14_vent_baffle as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_15_dry_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_17_dry_blower as ServiceProcedureSeed,
];
