// AUTO-GENERATED by backend/scripts/generate_procedure_registry.py — do not edit.
// Re-run after adding or removing procedure seed JSON files.


import insignia_dryer_tdre_bundles_nstdre75w1_service_test_entry from './seed/insignia_dryer_tdre/bundles/nstdre75w1-service-test-entry.json';
import samsung_fl_dryer_bb8700_bundles_samsungbb8700_dryer_error_recall from './seed/samsung_fl_dryer_bb8700/bundles/samsungbb8700-dryer-error-recall.json';
import samsung_fl_dryer_bb8700_bundles_samsungbb8700_dryer_smart_install_entry from './seed/samsung_fl_dryer_bb8700/bundles/samsungbb8700-dryer-smart-install-entry.json';
import samsung_fl_dryer_dv6000_bundles_samsungdv6000_error_recall from './seed/samsung_fl_dryer_dv6000/bundles/samsungdv6000-error-recall.json';
import samsung_fl_dryer_dv6000_bundles_samsungdv6000_smart_install_entry from './seed/samsung_fl_dryer_dv6000/bundles/samsungdv6000-smart-install-entry.json';
import samsung_fl_washer_bb8700_bundles_samsungbb8700_diagnostic_code_check from './seed/samsung_fl_washer_bb8700/bundles/samsungbb8700-diagnostic-code-check.json';
import samsung_fl_washer_bb8700_bundles_samsungbb8700_manual_check_mode from './seed/samsung_fl_washer_bb8700/bundles/samsungbb8700-manual-check-mode.json';
import samsung_fl_washer_bb8700_bundles_samsungbb8700_smart_install_entry from './seed/samsung_fl_washer_bb8700/bundles/samsungbb8700-smart-install-entry.json';
import samsung_tl_dryer_dv50_bundles_samsungtldv50_smart_install_entry from './seed/samsung_tl_dryer_dv50/bundles/samsungtldv50-smart-install-entry.json';
import samsung_tl_washer_a50_bundles_samsungtla50_diagnostic_code_check from './seed/samsung_tl_washer_a50/bundles/samsungtla50-diagnostic-code-check.json';
import samsung_tl_washer_a50_bundles_samsungtla50_manual_check_mode from './seed/samsung_tl_washer_a50/bundles/samsungtla50-manual-check-mode.json';
import samsung_tl_washer_a50_bundles_samsungtla50_smart_install_entry from './seed/samsung_tl_washer_a50/bundles/samsungtla50-smart-install-entry.json';
import whirlpool_acu_tl_dryer_bundles_w11416805_diagnostic_entry from './seed/whirlpool_acu_tl_dryer/bundles/w11416805-diagnostic-entry.json';
import whirlpool_acu_tl_dryer_bundles_w11798430_diagnostic_entry from './seed/whirlpool_acu_tl_dryer/bundles/w11798430-diagnostic-entry.json';
import whirlpool_ccu_dryer_bundles_w10680150_diagnostic_entry from './seed/whirlpool_ccu_dryer/bundles/w10680150-diagnostic-entry.json';
import whirlpool_ccu_dryer_bundles_w10881701_diagnostic_entry from './seed/whirlpool_ccu_dryer/bundles/w10881701-diagnostic-entry.json';
import whirlpool_ccu_dryer_bundles_w10881701_service_test_mode from './seed/whirlpool_ccu_dryer/bundles/w10881701-service-test-mode.json';
import whirlpool_ccu_dryer_bundles_w11169659_diagnostic_entry from './seed/whirlpool_ccu_dryer/bundles/w11169659-diagnostic-entry.json';
import whirlpool_ccu_dryer_bundles_w11169659_service_test_mode from './seed/whirlpool_ccu_dryer/bundles/w11169659-service-test-mode.json';
import whirlpool_centennial_dryer_bundles_w8178629_diagnostic_entry from './seed/whirlpool_centennial_dryer/bundles/w8178629-diagnostic-entry.json';
import whirlpool_dishwasher_acu_bundles_w11480208_service_diagnostic_entry from './seed/whirlpool_dishwasher_acu/bundles/w11480208-service-diagnostic-entry.json';
import whirlpool_dishwasher_acu_bundles_w11633848_service_diagnostic_entry from './seed/whirlpool_dishwasher_acu/bundles/w11633848-service-diagnostic-entry.json';
import whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry from './seed/whirlpool_duet_sport/bundles/w8178558-diagnostic-history-entry.json';
import whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test from './seed/whirlpool_duet_sport/bundles/w8178558-manual-diagnostic-test.json';
import whirlpool_duet_sport_dryer_bundles_w8178559_diagnostic_entry from './seed/whirlpool_duet_sport_dryer/bundles/w8178559-diagnostic-entry.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-dry-blower.json';
import whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan from './seed/whirlpool_fl_dd/bundles/w11169652-component-activation-vent-fan.json';
import whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump from './seed/whirlpool_fl_dd/bundles/w11169652-load-test-detergent-pump.json';
import whirlpool_fl_dd_bundles_w11169652_quick_service_cycle from './seed/whirlpool_fl_dd/bundles/w11169652-quick-service-cycle.json';
import whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry from './seed/whirlpool_fl_dd/bundles/w11169652-service-diagnostic-entry.json';
import whirlpool_fl_dd_bundles_w11169652_service_mode from './seed/whirlpool_fl_dd/bundles/w11169652-service-mode.json';
import whirlpool_mvw6200_bundles_w11416395_service_diagnostic_entry from './seed/whirlpool_mvw6200/bundles/w11416395-service-diagnostic-entry.json';
import whirlpool_mvw6200_bundles_w11416395_service_test_mode from './seed/whirlpool_mvw6200/bundles/w11416395-service-test-mode.json';
import whirlpool_tl_dd_bundles_w10864849_service_diagnostic_entry from './seed/whirlpool_tl_dd/bundles/w10864849-service-diagnostic-entry.json';
import whirlpool_tl_dd_bundles_w10864849_service_test_mode from './seed/whirlpool_tl_dd/bundles/w10864849-service-test-mode.json';
import whirlpool_tl_dd_bundles_w11697231_manual_test_mode from './seed/whirlpool_tl_dd/bundles/w11697231-manual-test-mode.json';
import whirlpool_tl_dd_bundles_w11697231_service_diagnostic_entry from './seed/whirlpool_tl_dd/bundles/w11697231-service-diagnostic-entry.json';
import whirlpool_tl_dd_4100_bundles_w11800233_automatic_test_mode from './seed/whirlpool_tl_dd_4100/bundles/w11800233-automatic-test-mode.json';
import whirlpool_tl_dd_4100_bundles_w11800233_service_diagnostic_entry from './seed/whirlpool_tl_dd_4100/bundles/w11800233-service-diagnostic-entry.json';
import whirlpool_tl_dd_5100_bundles_w11416787_component_activation from './seed/whirlpool_tl_dd_5100/bundles/w11416787-component-activation.json';
import whirlpool_tl_dd_5100_bundles_w11416787_service_diagnostic_entry from './seed/whirlpool_tl_dd_5100/bundles/w11416787-service-diagnostic-entry.json';
import whirlpool_tl_dd_6157_bundles_w11455152_automatic_test_mode from './seed/whirlpool_tl_dd_6157/bundles/w11455152-automatic-test-mode.json';
import whirlpool_tl_dd_6157_bundles_w11455152_service_diagnostic_entry from './seed/whirlpool_tl_dd_6157/bundles/w11455152-service-diagnostic-entry.json';

import insignia_dryer_tdre_nstdre75w1_belt_safety from './seed/insignia_dryer_tdre/nstdre75w1-belt-safety.json';
import insignia_dryer_tdre_nstdre75w1_communication from './seed/insignia_dryer_tdre/nstdre75w1-communication.json';
import insignia_dryer_tdre_nstdre75w1_door_switch from './seed/insignia_dryer_tdre/nstdre75w1-door-switch.json';
import insignia_dryer_tdre_nstdre75w1_flame_sensor from './seed/insignia_dryer_tdre/nstdre75w1-flame-sensor.json';
import insignia_dryer_tdre_nstdre75w1_gas_ignitor from './seed/insignia_dryer_tdre/nstdre75w1-gas-ignitor.json';
import insignia_dryer_tdre_nstdre75w1_gas_valve from './seed/insignia_dryer_tdre/nstdre75w1-gas-valve.json';
import insignia_dryer_tdre_nstdre75w1_heater_electric from './seed/insignia_dryer_tdre/nstdre75w1-heater-electric.json';
import insignia_dryer_tdre_nstdre75w1_heater_gas from './seed/insignia_dryer_tdre/nstdre75w1-heater-gas.json';
import insignia_dryer_tdre_nstdre75w1_hmi_test from './seed/insignia_dryer_tdre/nstdre75w1-hmi-test.json';
import insignia_dryer_tdre_nstdre75w1_humidity_sensor from './seed/insignia_dryer_tdre/nstdre75w1-humidity-sensor.json';
import insignia_dryer_tdre_nstdre75w1_motor_circuit from './seed/insignia_dryer_tdre/nstdre75w1-motor-circuit.json';
import insignia_dryer_tdre_nstdre75w1_outlet_thermistor from './seed/insignia_dryer_tdre/nstdre75w1-outlet-thermistor.json';
import insignia_dryer_tdre_nstdre75w1_thermal_cutoff from './seed/insignia_dryer_tdre/nstdre75w1-thermal-cutoff.json';
import insignia_dryer_tdre_nstdre75w1_thermal_hi_limit from './seed/insignia_dryer_tdre/nstdre75w1-thermal-hi-limit.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_belt_cutoff from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-belt-cutoff.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_door_switch from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-door-switch.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_flame_sensor from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-gas-flame-sensor.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_ignitor from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-gas-ignitor.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_valve from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-gas-valve.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_heater_electric from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-heater-electric.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_hmi from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-hmi.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_motor_circuit from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-motor-circuit.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_power from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-power.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_thermal_cutoff from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-thermal-cutoff.json';
import samsung_fl_dryer_bb8700_samsungbb8700_dryer_thermistor from './seed/samsung_fl_dryer_bb8700/samsungbb8700-dryer-thermistor.json';
import samsung_fl_dryer_dv6000_samsungdv6000_belt_cutoff from './seed/samsung_fl_dryer_dv6000/samsungdv6000-belt-cutoff.json';
import samsung_fl_dryer_dv6000_samsungdv6000_door_switch from './seed/samsung_fl_dryer_dv6000/samsungdv6000-door-switch.json';
import samsung_fl_dryer_dv6000_samsungdv6000_heat_pump_compressor from './seed/samsung_fl_dryer_dv6000/samsungdv6000-heat-pump-compressor.json';
import samsung_fl_dryer_dv6000_samsungdv6000_heater_electric from './seed/samsung_fl_dryer_dv6000/samsungdv6000-heater-electric.json';
import samsung_fl_dryer_dv6000_samsungdv6000_hmi from './seed/samsung_fl_dryer_dv6000/samsungdv6000-hmi.json';
import samsung_fl_dryer_dv6000_samsungdv6000_motor_circuit from './seed/samsung_fl_dryer_dv6000/samsungdv6000-motor-circuit.json';
import samsung_fl_dryer_dv6000_samsungdv6000_power from './seed/samsung_fl_dryer_dv6000/samsungdv6000-power.json';
import samsung_fl_dryer_dv6000_samsungdv6000_thermal_cutoff from './seed/samsung_fl_dryer_dv6000/samsungdv6000-thermal-cutoff.json';
import samsung_fl_dryer_dv6000_samsungdv6000_thermistor from './seed/samsung_fl_dryer_dv6000/samsungdv6000-thermistor.json';
import samsung_fl_washer_bb8700_samsungbb8700_communication from './seed/samsung_fl_washer_bb8700/samsungbb8700-communication.json';
import samsung_fl_washer_bb8700_samsungbb8700_door_lock from './seed/samsung_fl_washer_bb8700/samsungbb8700-door-lock.json';
import samsung_fl_washer_bb8700_samsungbb8700_drain_pump from './seed/samsung_fl_washer_bb8700/samsungbb8700-drain-pump.json';
import samsung_fl_washer_bb8700_samsungbb8700_inlet_valves from './seed/samsung_fl_washer_bb8700/samsungbb8700-inlet-valves.json';
import samsung_fl_washer_bb8700_samsungbb8700_motor_circuit from './seed/samsung_fl_washer_bb8700/samsungbb8700-motor-circuit.json';
import samsung_fl_washer_bb8700_samsungbb8700_overflow from './seed/samsung_fl_washer_bb8700/samsungbb8700-overflow.json';
import samsung_fl_washer_bb8700_samsungbb8700_power_supply from './seed/samsung_fl_washer_bb8700/samsungbb8700-power-supply.json';
import samsung_fl_washer_bb8700_samsungbb8700_wash_heater from './seed/samsung_fl_washer_bb8700/samsungbb8700-wash-heater.json';
import samsung_fl_washer_bb8700_samsungbb8700_wash_thermistor from './seed/samsung_fl_washer_bb8700/samsungbb8700-wash-thermistor.json';
import samsung_fl_washer_bb8700_samsungbb8700_water_level_sensor from './seed/samsung_fl_washer_bb8700/samsungbb8700-water-level-sensor.json';
import samsung_tl_dryer_dv50_samsungtldv50_belt_cutoff from './seed/samsung_tl_dryer_dv50/samsungtldv50-belt-cutoff.json';
import samsung_tl_dryer_dv50_samsungtldv50_door_switch from './seed/samsung_tl_dryer_dv50/samsungtldv50-door-switch.json';
import samsung_tl_dryer_dv50_samsungtldv50_gas_flame_sensor from './seed/samsung_tl_dryer_dv50/samsungtldv50-gas-flame-sensor.json';
import samsung_tl_dryer_dv50_samsungtldv50_gas_ignitor from './seed/samsung_tl_dryer_dv50/samsungtldv50-gas-ignitor.json';
import samsung_tl_dryer_dv50_samsungtldv50_gas_valve from './seed/samsung_tl_dryer_dv50/samsungtldv50-gas-valve.json';
import samsung_tl_dryer_dv50_samsungtldv50_heater_electric from './seed/samsung_tl_dryer_dv50/samsungtldv50-heater-electric.json';
import samsung_tl_dryer_dv50_samsungtldv50_hmi from './seed/samsung_tl_dryer_dv50/samsungtldv50-hmi.json';
import samsung_tl_dryer_dv50_samsungtldv50_motor_circuit from './seed/samsung_tl_dryer_dv50/samsungtldv50-motor-circuit.json';
import samsung_tl_dryer_dv50_samsungtldv50_power from './seed/samsung_tl_dryer_dv50/samsungtldv50-power.json';
import samsung_tl_dryer_dv50_samsungtldv50_thermal_cutoff from './seed/samsung_tl_dryer_dv50/samsungtldv50-thermal-cutoff.json';
import samsung_tl_dryer_dv50_samsungtldv50_thermistor from './seed/samsung_tl_dryer_dv50/samsungtldv50-thermistor.json';
import samsung_tl_washer_a50_samsungtla50_clutch from './seed/samsung_tl_washer_a50/samsungtla50-clutch.json';
import samsung_tl_washer_a50_samsungtla50_communication from './seed/samsung_tl_washer_a50/samsungtla50-communication.json';
import samsung_tl_washer_a50_samsungtla50_door_lock from './seed/samsung_tl_washer_a50/samsungtla50-door-lock.json';
import samsung_tl_washer_a50_samsungtla50_drain_pump from './seed/samsung_tl_washer_a50/samsungtla50-drain-pump.json';
import samsung_tl_washer_a50_samsungtla50_hmi_check from './seed/samsung_tl_washer_a50/samsungtla50-hmi-check.json';
import samsung_tl_washer_a50_samsungtla50_inlet_valves from './seed/samsung_tl_washer_a50/samsungtla50-inlet-valves.json';
import samsung_tl_washer_a50_samsungtla50_leak_check from './seed/samsung_tl_washer_a50/samsungtla50-leak-check.json';
import samsung_tl_washer_a50_samsungtla50_mems_sensor from './seed/samsung_tl_washer_a50/samsungtla50-mems-sensor.json';
import samsung_tl_washer_a50_samsungtla50_motor_circuit from './seed/samsung_tl_washer_a50/samsungtla50-motor-circuit.json';
import samsung_tl_washer_a50_samsungtla50_overflow from './seed/samsung_tl_washer_a50/samsungtla50-overflow.json';
import samsung_tl_washer_a50_samsungtla50_power_supply from './seed/samsung_tl_washer_a50/samsungtla50-power-supply.json';
import samsung_tl_washer_a50_samsungtla50_unbalance from './seed/samsung_tl_washer_a50/samsungtla50-unbalance.json';
import samsung_tl_washer_a50_samsungtla50_wash_heater from './seed/samsung_tl_washer_a50/samsungtla50-wash-heater.json';
import samsung_tl_washer_a50_samsungtla50_wash_thermistor from './seed/samsung_tl_washer_a50/samsungtla50-wash-thermistor.json';
import samsung_tl_washer_a50_samsungtla50_water_level_sensor from './seed/samsung_tl_washer_a50/samsungtla50-water-level-sensor.json';
import whirlpool_acu_tl_dryer_w11416805_acu_power from './seed/whirlpool_acu_tl_dryer/w11416805-acu-power.json';
import whirlpool_acu_tl_dryer_w11416805_door_switch from './seed/whirlpool_acu_tl_dryer/w11416805-door-switch.json';
import whirlpool_acu_tl_dryer_w11416805_drum_light from './seed/whirlpool_acu_tl_dryer/w11416805-drum-light.json';
import whirlpool_acu_tl_dryer_w11416805_gas_valve from './seed/whirlpool_acu_tl_dryer/w11416805-gas-valve.json';
import whirlpool_acu_tl_dryer_w11416805_heater_electric from './seed/whirlpool_acu_tl_dryer/w11416805-heater-electric.json';
import whirlpool_acu_tl_dryer_w11416805_heater_gas from './seed/whirlpool_acu_tl_dryer/w11416805-heater-gas.json';
import whirlpool_acu_tl_dryer_w11416805_hmi from './seed/whirlpool_acu_tl_dryer/w11416805-hmi.json';
import whirlpool_acu_tl_dryer_w11416805_moisture_sensor from './seed/whirlpool_acu_tl_dryer/w11416805-moisture-sensor.json';
import whirlpool_acu_tl_dryer_w11416805_motor_circuit from './seed/whirlpool_acu_tl_dryer/w11416805-motor-circuit.json';
import whirlpool_acu_tl_dryer_w11416805_supply_connections from './seed/whirlpool_acu_tl_dryer/w11416805-supply-connections.json';
import whirlpool_acu_tl_dryer_w11416805_thermal_cutoff from './seed/whirlpool_acu_tl_dryer/w11416805-thermal-cutoff.json';
import whirlpool_acu_tl_dryer_w11416805_thermal_fuse from './seed/whirlpool_acu_tl_dryer/w11416805-thermal-fuse.json';
import whirlpool_acu_tl_dryer_w11416805_thermistors from './seed/whirlpool_acu_tl_dryer/w11416805-thermistors.json';
import whirlpool_acu_tl_dryer_w11416805_water_valve from './seed/whirlpool_acu_tl_dryer/w11416805-water-valve.json';
import whirlpool_acu_tl_dryer_w11798430_acu_power from './seed/whirlpool_acu_tl_dryer/w11798430-acu-power.json';
import whirlpool_acu_tl_dryer_w11798430_door_switch from './seed/whirlpool_acu_tl_dryer/w11798430-door-switch.json';
import whirlpool_acu_tl_dryer_w11798430_drum_light from './seed/whirlpool_acu_tl_dryer/w11798430-drum-light.json';
import whirlpool_acu_tl_dryer_w11798430_gas_valve from './seed/whirlpool_acu_tl_dryer/w11798430-gas-valve.json';
import whirlpool_acu_tl_dryer_w11798430_heater_electric from './seed/whirlpool_acu_tl_dryer/w11798430-heater-electric.json';
import whirlpool_acu_tl_dryer_w11798430_heater_gas from './seed/whirlpool_acu_tl_dryer/w11798430-heater-gas.json';
import whirlpool_acu_tl_dryer_w11798430_hmi from './seed/whirlpool_acu_tl_dryer/w11798430-hmi.json';
import whirlpool_acu_tl_dryer_w11798430_motor_circuit from './seed/whirlpool_acu_tl_dryer/w11798430-motor-circuit.json';
import whirlpool_acu_tl_dryer_w11798430_supply_connections from './seed/whirlpool_acu_tl_dryer/w11798430-supply-connections.json';
import whirlpool_acu_tl_dryer_w11798430_thermal_cutoff from './seed/whirlpool_acu_tl_dryer/w11798430-thermal-cutoff.json';
import whirlpool_acu_tl_dryer_w11798430_thermal_fuse from './seed/whirlpool_acu_tl_dryer/w11798430-thermal-fuse.json';
import whirlpool_acu_tl_dryer_w11798430_thermistors from './seed/whirlpool_acu_tl_dryer/w11798430-thermistors.json';
import whirlpool_ccu_dryer_w10680150_button_indicator from './seed/whirlpool_ccu_dryer/w10680150-button-indicator.json';
import whirlpool_ccu_dryer_w10680150_ccu_power from './seed/whirlpool_ccu_dryer/w10680150-ccu-power.json';
import whirlpool_ccu_dryer_w10680150_door_switch from './seed/whirlpool_ccu_dryer/w10680150-door-switch.json';
import whirlpool_ccu_dryer_w10680150_dryness_adjust from './seed/whirlpool_ccu_dryer/w10680150-dryness-adjust.json';
import whirlpool_ccu_dryer_w10680150_gas_valve from './seed/whirlpool_ccu_dryer/w10680150-gas-valve.json';
import whirlpool_ccu_dryer_w10680150_heater_electric from './seed/whirlpool_ccu_dryer/w10680150-heater-electric.json';
import whirlpool_ccu_dryer_w10680150_heater_gas from './seed/whirlpool_ccu_dryer/w10680150-heater-gas.json';
import whirlpool_ccu_dryer_w10680150_moisture_sensor from './seed/whirlpool_ccu_dryer/w10680150-moisture-sensor.json';
import whirlpool_ccu_dryer_w10680150_motor_circuit from './seed/whirlpool_ccu_dryer/w10680150-motor-circuit.json';
import whirlpool_ccu_dryer_w10680150_supply_connections from './seed/whirlpool_ccu_dryer/w10680150-supply-connections.json';
import whirlpool_ccu_dryer_w10680150_thermal_cutoff from './seed/whirlpool_ccu_dryer/w10680150-thermal-cutoff.json';
import whirlpool_ccu_dryer_w10680150_thermal_fuse from './seed/whirlpool_ccu_dryer/w10680150-thermal-fuse.json';
import whirlpool_ccu_dryer_w10680150_thermistors from './seed/whirlpool_ccu_dryer/w10680150-thermistors.json';
import whirlpool_ccu_dryer_w10881701_acu_power from './seed/whirlpool_ccu_dryer/w10881701-acu-power.json';
import whirlpool_ccu_dryer_w10881701_button_indicator from './seed/whirlpool_ccu_dryer/w10881701-button-indicator.json';
import whirlpool_ccu_dryer_w10881701_door_switch from './seed/whirlpool_ccu_dryer/w10881701-door-switch.json';
import whirlpool_ccu_dryer_w10881701_drum_led from './seed/whirlpool_ccu_dryer/w10881701-drum-led.json';
import whirlpool_ccu_dryer_w10881701_dryness_adjust from './seed/whirlpool_ccu_dryer/w10881701-dryness-adjust.json';
import whirlpool_ccu_dryer_w10881701_gas_valve from './seed/whirlpool_ccu_dryer/w10881701-gas-valve.json';
import whirlpool_ccu_dryer_w10881701_heater_electric from './seed/whirlpool_ccu_dryer/w10881701-heater-electric.json';
import whirlpool_ccu_dryer_w10881701_heater_gas from './seed/whirlpool_ccu_dryer/w10881701-heater-gas.json';
import whirlpool_ccu_dryer_w10881701_moisture_sensor from './seed/whirlpool_ccu_dryer/w10881701-moisture-sensor.json';
import whirlpool_ccu_dryer_w10881701_motor_circuit from './seed/whirlpool_ccu_dryer/w10881701-motor-circuit.json';
import whirlpool_ccu_dryer_w10881701_service_leds from './seed/whirlpool_ccu_dryer/w10881701-service-leds.json';
import whirlpool_ccu_dryer_w10881701_supply_connections from './seed/whirlpool_ccu_dryer/w10881701-supply-connections.json';
import whirlpool_ccu_dryer_w10881701_thermal_cutoff from './seed/whirlpool_ccu_dryer/w10881701-thermal-cutoff.json';
import whirlpool_ccu_dryer_w10881701_thermal_fuse from './seed/whirlpool_ccu_dryer/w10881701-thermal-fuse.json';
import whirlpool_ccu_dryer_w10881701_thermistors from './seed/whirlpool_ccu_dryer/w10881701-thermistors.json';
import whirlpool_ccu_dryer_w10881701_water_valve from './seed/whirlpool_ccu_dryer/w10881701-water-valve.json';
import whirlpool_ccu_dryer_w11169659_acu_power from './seed/whirlpool_ccu_dryer/w11169659-acu-power.json';
import whirlpool_ccu_dryer_w11169659_drum_led from './seed/whirlpool_ccu_dryer/w11169659-drum-led.json';
import whirlpool_ccu_dryer_w11169659_heater_electric from './seed/whirlpool_ccu_dryer/w11169659-heater-electric.json';
import whirlpool_ccu_dryer_w11169659_moisture_sensor from './seed/whirlpool_ccu_dryer/w11169659-moisture-sensor.json';
import whirlpool_centennial_dryer_w8178629_door_switch from './seed/whirlpool_centennial_dryer/w8178629-door-switch.json';
import whirlpool_centennial_dryer_w8178629_drive_motor from './seed/whirlpool_centennial_dryer/w8178629-drive-motor.json';
import whirlpool_centennial_dryer_w8178629_electric_heater from './seed/whirlpool_centennial_dryer/w8178629-electric-heater.json';
import whirlpool_centennial_dryer_w8178629_electric_tco_inlet from './seed/whirlpool_centennial_dryer/w8178629-electric-tco-inlet.json';
import whirlpool_centennial_dryer_w8178629_flame_sensor from './seed/whirlpool_centennial_dryer/w8178629-flame-sensor.json';
import whirlpool_centennial_dryer_w8178629_gas_coils from './seed/whirlpool_centennial_dryer/w8178629-gas-coils.json';
import whirlpool_centennial_dryer_w8178629_gas_hilimit_cutoff from './seed/whirlpool_centennial_dryer/w8178629-gas-hilimit-cutoff.json';
import whirlpool_centennial_dryer_w8178629_gas_ignitor from './seed/whirlpool_centennial_dryer/w8178629-gas-ignitor.json';
import whirlpool_centennial_dryer_w8178629_supply_connections from './seed/whirlpool_centennial_dryer/w8178629-supply-connections.json';
import whirlpool_centennial_dryer_w8178629_thermal_fuse_exhaust from './seed/whirlpool_centennial_dryer/w8178629-thermal-fuse-exhaust.json';
import whirlpool_centennial_dryer_w8178629_timer_motor from './seed/whirlpool_centennial_dryer/w8178629-timer-motor.json';
import whirlpool_dishwasher_acu_w11480208_dc_fan from './seed/whirlpool_dishwasher_acu/w11480208-dc-fan.json';
import whirlpool_dishwasher_acu_w11480208_diverter_motor from './seed/whirlpool_dishwasher_acu/w11480208-diverter-motor.json';
import whirlpool_dishwasher_acu_w11480208_door_switch from './seed/whirlpool_dishwasher_acu/w11480208-door-switch.json';
import whirlpool_dishwasher_acu_w11480208_drain_motor_vsm from './seed/whirlpool_dishwasher_acu/w11480208-drain-motor-vsm.json';
import whirlpool_dishwasher_acu_w11480208_heater from './seed/whirlpool_dishwasher_acu/w11480208-heater.json';
import whirlpool_dishwasher_acu_w11480208_interior_led from './seed/whirlpool_dishwasher_acu/w11480208-interior-led.json';
import whirlpool_dishwasher_acu_w11480208_overfill_switch from './seed/whirlpool_dishwasher_acu/w11480208-overfill-switch.json';
import whirlpool_dishwasher_acu_w11480208_wash_motor_vsm from './seed/whirlpool_dishwasher_acu/w11480208-wash-motor-vsm.json';
import whirlpool_dishwasher_acu_w11499711_wash_motor_ssm from './seed/whirlpool_dishwasher_acu/w11499711-wash-motor-ssm.json';
import whirlpool_dishwasher_acu_w11633848_acu_power from './seed/whirlpool_dishwasher_acu/w11633848-acu-power.json';
import whirlpool_dishwasher_acu_w11633848_dc_fan from './seed/whirlpool_dishwasher_acu/w11633848-dc-fan.json';
import whirlpool_dishwasher_acu_w11633848_dispenser from './seed/whirlpool_dishwasher_acu/w11633848-dispenser.json';
import whirlpool_dishwasher_acu_w11633848_diverter_motor from './seed/whirlpool_dishwasher_acu/w11633848-diverter-motor.json';
import whirlpool_dishwasher_acu_w11633848_diverter_sensor from './seed/whirlpool_dishwasher_acu/w11633848-diverter-sensor.json';
import whirlpool_dishwasher_acu_w11633848_door_switch from './seed/whirlpool_dishwasher_acu/w11633848-door-switch.json';
import whirlpool_dishwasher_acu_w11633848_drain_motor from './seed/whirlpool_dishwasher_acu/w11633848-drain-motor.json';
import whirlpool_dishwasher_acu_w11633848_fill_valve from './seed/whirlpool_dishwasher_acu/w11633848-fill-valve.json';
import whirlpool_dishwasher_acu_w11633848_heater from './seed/whirlpool_dishwasher_acu/w11633848-heater.json';
import whirlpool_dishwasher_acu_w11633848_overfill_switch from './seed/whirlpool_dishwasher_acu/w11633848-overfill-switch.json';
import whirlpool_dishwasher_acu_w11633848_owi_sensor from './seed/whirlpool_dishwasher_acu/w11633848-owi-sensor.json';
import whirlpool_dishwasher_acu_w11633848_triac_fuse from './seed/whirlpool_dishwasher_acu/w11633848-triac-fuse.json';
import whirlpool_dishwasher_acu_w11633848_wash_motor from './seed/whirlpool_dishwasher_acu/w11633848-wash-motor.json';
import whirlpool_dishwasher_acu_w11794121_door_opening_system from './seed/whirlpool_dishwasher_acu/w11794121-door-opening-system.json';
import whirlpool_duet_sport_w8178558_dispenser_motor from './seed/whirlpool_duet_sport/w8178558-dispenser-motor.json';
import whirlpool_duet_sport_w8178558_door_lock from './seed/whirlpool_duet_sport/w8178558-door-lock.json';
import whirlpool_duet_sport_w8178558_drain_pump from './seed/whirlpool_duet_sport/w8178558-drain-pump.json';
import whirlpool_duet_sport_w8178558_inlet_valves from './seed/whirlpool_duet_sport/w8178558-inlet-valves.json';
import whirlpool_duet_sport_w8178558_interlock_switch from './seed/whirlpool_duet_sport/w8178558-interlock-switch.json';
import whirlpool_duet_sport_w8178558_motor_circuit from './seed/whirlpool_duet_sport/w8178558-motor-circuit.json';
import whirlpool_duet_sport_w8178558_pressure_switch from './seed/whirlpool_duet_sport/w8178558-pressure-switch.json';
import whirlpool_duet_sport_w8178558_wash_heater from './seed/whirlpool_duet_sport/w8178558-wash-heater.json';
import whirlpool_duet_sport_w8178558_wash_ntc from './seed/whirlpool_duet_sport/w8178558-wash-ntc.json';
import whirlpool_duet_sport_dryer_w8178559_button_indicator from './seed/whirlpool_duet_sport_dryer/w8178559-button-indicator.json';
import whirlpool_duet_sport_dryer_w8178559_door_switch from './seed/whirlpool_duet_sport_dryer/w8178559-door-switch.json';
import whirlpool_duet_sport_dryer_w8178559_dryness_adjust from './seed/whirlpool_duet_sport_dryer/w8178559-dryness-adjust.json';
import whirlpool_duet_sport_dryer_w8178559_exhaust_thermistor from './seed/whirlpool_duet_sport_dryer/w8178559-exhaust-thermistor.json';
import whirlpool_duet_sport_dryer_w8178559_gas_ignitor from './seed/whirlpool_duet_sport_dryer/w8178559-gas-ignitor.json';
import whirlpool_duet_sport_dryer_w8178559_gas_valve from './seed/whirlpool_duet_sport_dryer/w8178559-gas-valve.json';
import whirlpool_duet_sport_dryer_w8178559_heater_electric from './seed/whirlpool_duet_sport_dryer/w8178559-heater-electric.json';
import whirlpool_duet_sport_dryer_w8178559_heater_gas from './seed/whirlpool_duet_sport_dryer/w8178559-heater-gas.json';
import whirlpool_duet_sport_dryer_w8178559_moisture_sensor from './seed/whirlpool_duet_sport_dryer/w8178559-moisture-sensor.json';
import whirlpool_duet_sport_dryer_w8178559_motor_circuit from './seed/whirlpool_duet_sport_dryer/w8178559-motor-circuit.json';
import whirlpool_duet_sport_dryer_w8178559_supply_connections from './seed/whirlpool_duet_sport_dryer/w8178559-supply-connections.json';
import whirlpool_duet_sport_dryer_w8178559_thermal_cutoff from './seed/whirlpool_duet_sport_dryer/w8178559-thermal-cutoff.json';
import whirlpool_duet_sport_dryer_w8178559_thermal_fuse from './seed/whirlpool_duet_sport_dryer/w8178559-thermal-fuse.json';
import whirlpool_fl_dd_w11169652_test_01_acu_power from './seed/whirlpool_fl_dd/w11169652-test-01-acu-power.json';
import whirlpool_fl_dd_w11169652_test_02_hmi from './seed/whirlpool_fl_dd/w11169652-test-02-hmi.json';
import whirlpool_fl_dd_w11169652_test_03_motor from './seed/whirlpool_fl_dd/w11169652-test-03-motor.json';
import whirlpool_fl_dd_w11169652_test_04_door_lock from './seed/whirlpool_fl_dd/w11169652-test-04-door-lock.json';
import whirlpool_fl_dd_w11169652_test_05_drum_light from './seed/whirlpool_fl_dd/w11169652-test-05-drum-light.json';
import whirlpool_fl_dd_w11169652_test_06_inlet_valves from './seed/whirlpool_fl_dd/w11169652-test-06-inlet-valves.json';
import whirlpool_fl_dd_w11169652_test_07_water_level_sensor from './seed/whirlpool_fl_dd/w11169652-test-07-water-level-sensor.json';
import whirlpool_fl_dd_w11169652_test_08_drain_pump from './seed/whirlpool_fl_dd/w11169652-test-08-drain-pump.json';
import whirlpool_fl_dd_w11169652_test_09_wash_heater from './seed/whirlpool_fl_dd/w11169652-test-09-wash-heater.json';
import whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-10-wash-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser from './seed/whirlpool_fl_dd/w11169652-test-11a-single-dose-dispenser.json';
import whirlpool_fl_dd_w11169652_test_11b_dosing_pump from './seed/whirlpool_fl_dd/w11169652-test-11b-dosing-pump.json';
import whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser from './seed/whirlpool_fl_dd/w11169652-test-12a-bulk-dispenser.json';
import whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing from './seed/whirlpool_fl_dd/w11169652-test-12b-bulk-level-sensing.json';
import whirlpool_fl_dd_w11169652_test_13_vent_fan from './seed/whirlpool_fl_dd/w11169652-test-13-vent-fan.json';
import whirlpool_fl_dd_w11169652_test_14_vent_baffle from './seed/whirlpool_fl_dd/w11169652-test-14-vent-baffle.json';
import whirlpool_fl_dd_w11169652_test_15_dry_heater from './seed/whirlpool_fl_dd/w11169652-test-15-dry-heater.json';
import whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor from './seed/whirlpool_fl_dd/w11169652-test-16-dry-temp-sensor.json';
import whirlpool_fl_dd_w11169652_test_17_dry_blower from './seed/whirlpool_fl_dd/w11169652-test-17-dry-blower.json';
import whirlpool_mvw6200_w11416395_test_01_acu_power from './seed/whirlpool_mvw6200/w11416395-test-01-acu-power.json';
import whirlpool_mvw6200_w11416395_test_02_valves from './seed/whirlpool_mvw6200/w11416395-test-02-valves.json';
import whirlpool_mvw6200_w11416395_test_03_drive_system from './seed/whirlpool_mvw6200/w11416395-test-03-drive-system.json';
import whirlpool_mvw6200_w11416395_test_03a_shifter from './seed/whirlpool_mvw6200/w11416395-test-03a-shifter.json';
import whirlpool_mvw6200_w11416395_test_03b_motor from './seed/whirlpool_mvw6200/w11416395-test-03b-motor.json';
import whirlpool_mvw6200_w11416395_test_04_hmi from './seed/whirlpool_mvw6200/w11416395-test-04-hmi.json';
import whirlpool_mvw6200_w11416395_test_05_temp_thermistor from './seed/whirlpool_mvw6200/w11416395-test-05-temp-thermistor.json';
import whirlpool_mvw6200_w11416395_test_06_water_level from './seed/whirlpool_mvw6200/w11416395-test-06-water-level.json';
import whirlpool_mvw6200_w11416395_test_07_drain_pump from './seed/whirlpool_mvw6200/w11416395-test-07-drain-pump.json';
import whirlpool_mvw6200_w11416395_test_08_lid_lock from './seed/whirlpool_mvw6200/w11416395-test-08-lid-lock.json';
import whirlpool_tl_dd_w10864849_test_01_acu_power from './seed/whirlpool_tl_dd/w10864849-test-01-acu-power.json';
import whirlpool_tl_dd_w10864849_test_02_valves from './seed/whirlpool_tl_dd/w10864849-test-02-valves.json';
import whirlpool_tl_dd_w10864849_test_03_drive_system from './seed/whirlpool_tl_dd/w10864849-test-03-drive-system.json';
import whirlpool_tl_dd_w10864849_test_03a_shifter from './seed/whirlpool_tl_dd/w10864849-test-03a-shifter.json';
import whirlpool_tl_dd_w10864849_test_03b_motor from './seed/whirlpool_tl_dd/w10864849-test-03b-motor.json';
import whirlpool_tl_dd_w10864849_test_04_keys_encoders from './seed/whirlpool_tl_dd/w10864849-test-04-keys-encoders.json';
import whirlpool_tl_dd_w10864849_test_05_temp_thermistor from './seed/whirlpool_tl_dd/w10864849-test-05-temp-thermistor.json';
import whirlpool_tl_dd_w10864849_test_06_water_level from './seed/whirlpool_tl_dd/w10864849-test-06-water-level.json';
import whirlpool_tl_dd_w10864849_test_07_drain_recirc_pump from './seed/whirlpool_tl_dd/w10864849-test-07-drain-recirc-pump.json';
import whirlpool_tl_dd_w10864849_test_08_lid_lock from './seed/whirlpool_tl_dd/w10864849-test-08-lid-lock.json';
import whirlpool_tl_dd_w10864849_test_09_heater from './seed/whirlpool_tl_dd/w10864849-test-09-heater.json';
import whirlpool_tl_dd_w10864849_test_10_service_leds from './seed/whirlpool_tl_dd/w10864849-test-10-service-leds.json';
import whirlpool_tl_dd_w10864849_test_11_basket_light from './seed/whirlpool_tl_dd/w10864849-test-11-basket-light.json';
import whirlpool_tl_dd_w10864849_test_12_bulk_dispense from './seed/whirlpool_tl_dd/w10864849-test-12-bulk-dispense.json';
import whirlpool_tl_dd_w11697231_test_01_acu_power from './seed/whirlpool_tl_dd/w11697231-test-01-acu-power.json';
import whirlpool_tl_dd_w11697231_test_02_valves from './seed/whirlpool_tl_dd/w11697231-test-02-valves.json';
import whirlpool_tl_dd_w11697231_test_03_drive_system from './seed/whirlpool_tl_dd/w11697231-test-03-drive-system.json';
import whirlpool_tl_dd_w11697231_test_03a_shifter from './seed/whirlpool_tl_dd/w11697231-test-03a-shifter.json';
import whirlpool_tl_dd_w11697231_test_03b_motor from './seed/whirlpool_tl_dd/w11697231-test-03b-motor.json';
import whirlpool_tl_dd_w11697231_test_04_console_indicators from './seed/whirlpool_tl_dd/w11697231-test-04-console-indicators.json';
import whirlpool_tl_dd_w11697231_test_05_temp_thermistor from './seed/whirlpool_tl_dd/w11697231-test-05-temp-thermistor.json';
import whirlpool_tl_dd_w11697231_test_06_water_level from './seed/whirlpool_tl_dd/w11697231-test-06-water-level.json';
import whirlpool_tl_dd_w11697231_test_07_drain_pump from './seed/whirlpool_tl_dd/w11697231-test-07-drain-pump.json';
import whirlpool_tl_dd_w11697231_test_08_lid_lock from './seed/whirlpool_tl_dd/w11697231-test-08-lid-lock.json';
import whirlpool_tl_dd_4100_w11800233_test_01_acu_power from './seed/whirlpool_tl_dd_4100/w11800233-test-01-acu-power.json';
import whirlpool_tl_dd_4100_w11800233_test_02_valves from './seed/whirlpool_tl_dd_4100/w11800233-test-02-valves.json';
import whirlpool_tl_dd_4100_w11800233_test_03_drive_system from './seed/whirlpool_tl_dd_4100/w11800233-test-03-drive-system.json';
import whirlpool_tl_dd_4100_w11800233_test_03a_shifter from './seed/whirlpool_tl_dd_4100/w11800233-test-03a-shifter.json';
import whirlpool_tl_dd_4100_w11800233_test_03b_motor from './seed/whirlpool_tl_dd_4100/w11800233-test-03b-motor.json';
import whirlpool_tl_dd_4100_w11800233_test_04_hmi from './seed/whirlpool_tl_dd_4100/w11800233-test-04-hmi.json';
import whirlpool_tl_dd_4100_w11800233_test_05_water_level from './seed/whirlpool_tl_dd_4100/w11800233-test-05-water-level.json';
import whirlpool_tl_dd_4100_w11800233_test_06_drain_pump from './seed/whirlpool_tl_dd_4100/w11800233-test-06-drain-pump.json';
import whirlpool_tl_dd_4100_w11800233_test_07_lid_lock from './seed/whirlpool_tl_dd_4100/w11800233-test-07-lid-lock.json';
import whirlpool_tl_dd_5100_w11416787_test_01_acu_power from './seed/whirlpool_tl_dd_5100/w11416787-test-01-acu-power.json';
import whirlpool_tl_dd_5100_w11416787_test_02_valves from './seed/whirlpool_tl_dd_5100/w11416787-test-02-valves.json';
import whirlpool_tl_dd_5100_w11416787_test_03_drive_system from './seed/whirlpool_tl_dd_5100/w11416787-test-03-drive-system.json';
import whirlpool_tl_dd_5100_w11416787_test_03a_shifter from './seed/whirlpool_tl_dd_5100/w11416787-test-03a-shifter.json';
import whirlpool_tl_dd_5100_w11416787_test_03b_motor from './seed/whirlpool_tl_dd_5100/w11416787-test-03b-motor.json';
import whirlpool_tl_dd_5100_w11416787_test_04_hmi from './seed/whirlpool_tl_dd_5100/w11416787-test-04-hmi.json';
import whirlpool_tl_dd_5100_w11416787_test_05_temp_thermistor from './seed/whirlpool_tl_dd_5100/w11416787-test-05-temp-thermistor.json';
import whirlpool_tl_dd_5100_w11416787_test_06_water_level from './seed/whirlpool_tl_dd_5100/w11416787-test-06-water-level.json';
import whirlpool_tl_dd_5100_w11416787_test_07_drain_recirc_pump from './seed/whirlpool_tl_dd_5100/w11416787-test-07-drain-recirc-pump.json';
import whirlpool_tl_dd_5100_w11416787_test_08_lid_lock from './seed/whirlpool_tl_dd_5100/w11416787-test-08-lid-lock.json';
import whirlpool_tl_dd_5100_w11416787_test_09_load_and_go from './seed/whirlpool_tl_dd_5100/w11416787-test-09-load-and-go.json';
import whirlpool_tl_dd_6157_w11455152_test_01_acu_power from './seed/whirlpool_tl_dd_6157/w11455152-test-01-acu-power.json';
import whirlpool_tl_dd_6157_w11455152_test_02_valves from './seed/whirlpool_tl_dd_6157/w11455152-test-02-valves.json';
import whirlpool_tl_dd_6157_w11455152_test_03_drive_system from './seed/whirlpool_tl_dd_6157/w11455152-test-03-drive-system.json';
import whirlpool_tl_dd_6157_w11455152_test_03a_shifter from './seed/whirlpool_tl_dd_6157/w11455152-test-03a-shifter.json';
import whirlpool_tl_dd_6157_w11455152_test_03b_motor from './seed/whirlpool_tl_dd_6157/w11455152-test-03b-motor.json';
import whirlpool_tl_dd_6157_w11455152_test_04_hmi from './seed/whirlpool_tl_dd_6157/w11455152-test-04-hmi.json';
import whirlpool_tl_dd_6157_w11455152_test_05_water_level from './seed/whirlpool_tl_dd_6157/w11455152-test-05-water-level.json';
import whirlpool_tl_dd_6157_w11455152_test_06_drain_pump from './seed/whirlpool_tl_dd_6157/w11455152-test-06-drain-pump.json';
import whirlpool_tl_dd_6157_w11455152_test_07_lid_lock from './seed/whirlpool_tl_dd_6157/w11455152-test-07-lid-lock.json';

import type { ServiceModeBundle, ServiceProcedureSeed } from './types';

export const GENERATED_SERVICE_MODE_BUNDLES: ServiceModeBundle[] = [
  insignia_dryer_tdre_bundles_nstdre75w1_service_test_entry as ServiceModeBundle,
  samsung_fl_dryer_bb8700_bundles_samsungbb8700_dryer_error_recall as ServiceModeBundle,
  samsung_fl_dryer_bb8700_bundles_samsungbb8700_dryer_smart_install_entry as ServiceModeBundle,
  samsung_fl_dryer_dv6000_bundles_samsungdv6000_error_recall as ServiceModeBundle,
  samsung_fl_dryer_dv6000_bundles_samsungdv6000_smart_install_entry as ServiceModeBundle,
  samsung_fl_washer_bb8700_bundles_samsungbb8700_diagnostic_code_check as ServiceModeBundle,
  samsung_fl_washer_bb8700_bundles_samsungbb8700_manual_check_mode as ServiceModeBundle,
  samsung_fl_washer_bb8700_bundles_samsungbb8700_smart_install_entry as ServiceModeBundle,
  samsung_tl_dryer_dv50_bundles_samsungtldv50_smart_install_entry as ServiceModeBundle,
  samsung_tl_washer_a50_bundles_samsungtla50_diagnostic_code_check as ServiceModeBundle,
  samsung_tl_washer_a50_bundles_samsungtla50_manual_check_mode as ServiceModeBundle,
  samsung_tl_washer_a50_bundles_samsungtla50_smart_install_entry as ServiceModeBundle,
  whirlpool_acu_tl_dryer_bundles_w11416805_diagnostic_entry as ServiceModeBundle,
  whirlpool_acu_tl_dryer_bundles_w11798430_diagnostic_entry as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w10680150_diagnostic_entry as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w10881701_diagnostic_entry as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w10881701_service_test_mode as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w11169659_diagnostic_entry as ServiceModeBundle,
  whirlpool_ccu_dryer_bundles_w11169659_service_test_mode as ServiceModeBundle,
  whirlpool_centennial_dryer_bundles_w8178629_diagnostic_entry as ServiceModeBundle,
  whirlpool_dishwasher_acu_bundles_w11480208_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_dishwasher_acu_bundles_w11633848_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_duet_sport_bundles_w8178558_diagnostic_history_entry as ServiceModeBundle,
  whirlpool_duet_sport_bundles_w8178558_manual_diagnostic_test as ServiceModeBundle,
  whirlpool_duet_sport_dryer_bundles_w8178559_diagnostic_entry as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_dry_blower as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_component_activation_vent_fan as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_load_test_detergent_pump as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_quick_service_cycle as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_fl_dd_bundles_w11169652_service_mode as ServiceModeBundle,
  whirlpool_mvw6200_bundles_w11416395_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_mvw6200_bundles_w11416395_service_test_mode as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w10864849_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w10864849_service_test_mode as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w11697231_manual_test_mode as ServiceModeBundle,
  whirlpool_tl_dd_bundles_w11697231_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_tl_dd_4100_bundles_w11800233_automatic_test_mode as ServiceModeBundle,
  whirlpool_tl_dd_4100_bundles_w11800233_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_tl_dd_5100_bundles_w11416787_component_activation as ServiceModeBundle,
  whirlpool_tl_dd_5100_bundles_w11416787_service_diagnostic_entry as ServiceModeBundle,
  whirlpool_tl_dd_6157_bundles_w11455152_automatic_test_mode as ServiceModeBundle,
  whirlpool_tl_dd_6157_bundles_w11455152_service_diagnostic_entry as ServiceModeBundle,
];

export const GENERATED_PROCEDURE_SEEDS: ServiceProcedureSeed[] = [
  insignia_dryer_tdre_nstdre75w1_belt_safety as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_communication as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_door_switch as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_flame_sensor as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_gas_ignitor as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_gas_valve as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_heater_electric as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_heater_gas as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_hmi_test as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_humidity_sensor as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_motor_circuit as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_outlet_thermistor as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_thermal_cutoff as ServiceProcedureSeed,
  insignia_dryer_tdre_nstdre75w1_thermal_hi_limit as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_belt_cutoff as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_door_switch as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_flame_sensor as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_ignitor as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_gas_valve as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_heater_electric as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_hmi as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_motor_circuit as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_power as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_thermal_cutoff as ServiceProcedureSeed,
  samsung_fl_dryer_bb8700_samsungbb8700_dryer_thermistor as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_belt_cutoff as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_door_switch as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_heat_pump_compressor as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_heater_electric as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_hmi as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_motor_circuit as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_power as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_thermal_cutoff as ServiceProcedureSeed,
  samsung_fl_dryer_dv6000_samsungdv6000_thermistor as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_communication as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_door_lock as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_drain_pump as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_inlet_valves as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_motor_circuit as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_overflow as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_power_supply as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_wash_heater as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_wash_thermistor as ServiceProcedureSeed,
  samsung_fl_washer_bb8700_samsungbb8700_water_level_sensor as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_belt_cutoff as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_door_switch as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_gas_flame_sensor as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_gas_ignitor as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_gas_valve as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_heater_electric as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_hmi as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_motor_circuit as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_power as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_thermal_cutoff as ServiceProcedureSeed,
  samsung_tl_dryer_dv50_samsungtldv50_thermistor as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_clutch as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_communication as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_door_lock as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_drain_pump as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_hmi_check as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_inlet_valves as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_leak_check as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_mems_sensor as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_motor_circuit as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_overflow as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_power_supply as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_unbalance as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_wash_heater as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_wash_thermistor as ServiceProcedureSeed,
  samsung_tl_washer_a50_samsungtla50_water_level_sensor as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_acu_power as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_door_switch as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_drum_light as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_gas_valve as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_heater_electric as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_heater_gas as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_hmi as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_moisture_sensor as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_motor_circuit as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_supply_connections as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermal_fuse as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_thermistors as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11416805_water_valve as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_acu_power as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_door_switch as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_drum_light as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_gas_valve as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_heater_electric as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_heater_gas as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_hmi as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_motor_circuit as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_supply_connections as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_thermal_fuse as ServiceProcedureSeed,
  whirlpool_acu_tl_dryer_w11798430_thermistors as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_button_indicator as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_ccu_power as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_door_switch as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_dryness_adjust as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_gas_valve as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_heater_electric as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_heater_gas as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_moisture_sensor as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_motor_circuit as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_supply_connections as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermal_fuse as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10680150_thermistors as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_acu_power as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_button_indicator as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_door_switch as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_drum_led as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_dryness_adjust as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_gas_valve as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_heater_electric as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_heater_gas as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_moisture_sensor as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_motor_circuit as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_service_leds as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_supply_connections as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_thermal_fuse as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_thermistors as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w10881701_water_valve as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w11169659_acu_power as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w11169659_drum_led as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w11169659_heater_electric as ServiceProcedureSeed,
  whirlpool_ccu_dryer_w11169659_moisture_sensor as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_door_switch as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_drive_motor as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_electric_heater as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_electric_tco_inlet as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_flame_sensor as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_gas_coils as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_gas_hilimit_cutoff as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_gas_ignitor as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_supply_connections as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_thermal_fuse_exhaust as ServiceProcedureSeed,
  whirlpool_centennial_dryer_w8178629_timer_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_dc_fan as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_diverter_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_door_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_drain_motor_vsm as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_heater as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_interior_led as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_overfill_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11480208_wash_motor_vsm as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11499711_wash_motor_ssm as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_acu_power as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_dc_fan as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_dispenser as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_diverter_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_diverter_sensor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_door_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_drain_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_fill_valve as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_heater as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_overfill_switch as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_owi_sensor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_triac_fuse as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11633848_wash_motor as ServiceProcedureSeed,
  whirlpool_dishwasher_acu_w11794121_door_opening_system as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_dispenser_motor as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_door_lock as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_drain_pump as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_inlet_valves as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_interlock_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_motor_circuit as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_pressure_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_heater as ServiceProcedureSeed,
  whirlpool_duet_sport_w8178558_wash_ntc as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_button_indicator as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_door_switch as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_dryness_adjust as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_exhaust_thermistor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_gas_ignitor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_gas_valve as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_heater_electric as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_heater_gas as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_moisture_sensor as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_motor_circuit as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_supply_connections as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_thermal_cutoff as ServiceProcedureSeed,
  whirlpool_duet_sport_dryer_w8178559_thermal_fuse as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_02_hmi as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_03_motor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_04_door_lock as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_05_drum_light as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_06_inlet_valves as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_07_water_level_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_08_drain_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_09_wash_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_10_wash_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11a_single_dose_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_11b_dosing_pump as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12a_bulk_dispenser as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_12b_bulk_level_sensing as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_13_vent_fan as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_14_vent_baffle as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_15_dry_heater as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_16_dry_temp_sensor as ServiceProcedureSeed,
  whirlpool_fl_dd_w11169652_test_17_dry_blower as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_02_valves as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_03b_motor as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_04_hmi as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_05_temp_thermistor as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_06_water_level as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_07_drain_pump as ServiceProcedureSeed,
  whirlpool_mvw6200_w11416395_test_08_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_04_keys_encoders as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_05_temp_thermistor as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_06_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_07_drain_recirc_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_08_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_09_heater as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_10_service_leds as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_11_basket_light as ServiceProcedureSeed,
  whirlpool_tl_dd_w10864849_test_12_bulk_dispense as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_04_console_indicators as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_05_temp_thermistor as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_06_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_07_drain_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_w11697231_test_08_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_04_hmi as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_05_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_06_drain_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_4100_w11800233_test_07_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_04_hmi as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_05_temp_thermistor as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_06_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_07_drain_recirc_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_08_lid_lock as ServiceProcedureSeed,
  whirlpool_tl_dd_5100_w11416787_test_09_load_and_go as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_01_acu_power as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_02_valves as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_03_drive_system as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_03a_shifter as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_03b_motor as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_04_hmi as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_05_water_level as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_06_drain_pump as ServiceProcedureSeed,
  whirlpool_tl_dd_6157_w11455152_test_07_lid_lock as ServiceProcedureSeed,
];
