import type { ProcedureImage } from './types';

const ASSET_BASE = '/images/procedures/whirlpool_fl_dd';

/** Cropped OEM figures for W11169652 — generated by crop_w11169652_procedure_figures.py */
export const W11169652_DIAGRAMS: Record<string, ProcedureImage> = {
  'w11169652-rfi-filter-figure1': {
    id: 'w11169652-rfi-filter-figure1',
    caption: 'RFI filter — line in/out (Figure 1, manual p. 3-6)',
    assetPath: `${ASSET_BASE}/w11169652-rfi-filter-figure1.png`,
  },
  'w11169652-acu-pinout-figure2': {
    id: 'w11169652-acu-pinout-figure2',
    caption: 'ACU connectors & pinouts (Figure 2, manual p. 3-7)',
    assetPath: `${ASSET_BASE}/w11169652-acu-pinout-figure2.png`,
  },
  'w11169652-motor-j6-location': {
    id: 'w11169652-motor-j6-location',
    caption: 'Motor harness connector J6 on ACU (TEST #3)',
    assetPath: `${ASSET_BASE}/w11169652-motor-j6-location.png`,
  },
  'w11169652-drum-light-j16-location': {
    id: 'w11169652-drum-light-j16-location',
    caption: 'Drum light connector J16 on ACU (TEST #5)',
    assetPath: `${ASSET_BASE}/w11169652-drum-light-j16-location.png`,
  },
  'w11169652-inlet-valves-strip': {
    id: 'w11169652-inlet-valves-strip',
    caption: 'Inlet water valve strip circuit — J8 (TEST #6)',
    assetPath: `${ASSET_BASE}/w11169652-inlet-valves-strip.png`,
  },
  'w11169652-water-level-j14': {
    id: 'w11169652-water-level-j14',
    caption: 'Water level sensor / APS — J14 (TEST #7)',
    assetPath: `${ASSET_BASE}/w11169652-water-level-j14.png`,
  },
  'w11169652-wash-heater-j3-location': {
    id: 'w11169652-wash-heater-j3-location',
    caption: 'Wash heater & temperature sensor — J3 / J15 (TEST #9–10)',
    assetPath: `${ASSET_BASE}/w11169652-wash-heater-j3-location.png`,
  },
  'w11169652-dosing-pump-strip': {
    id: 'w11169652-dosing-pump-strip',
    caption: 'Detergent dosing pump strip circuit — J10 (TEST #11B)',
    assetPath: `${ASSET_BASE}/w11169652-dosing-pump-strip.png`,
  },
  'w11169652-bulk-level-strip': {
    id: 'w11169652-bulk-level-strip',
    caption: 'Bulk dispenser level sensing — J17 (TEST #12B)',
    assetPath: `${ASSET_BASE}/w11169652-bulk-level-strip.png`,
  },
  'w11169652-vent-fan-j12-strip': {
    id: 'w11169652-vent-fan-j12-strip',
    caption: 'Vent fan / blower strip circuit — J12 (TEST #13 / #17)',
    assetPath: `${ASSET_BASE}/w11169652-vent-fan-j12-strip.png`,
  },
  'w11169652-baffle-j9-location': {
    id: 'w11169652-baffle-j9-location',
    caption: 'Vent baffle solenoid — J9 (TEST #14)',
    assetPath: `${ASSET_BASE}/w11169652-baffle-j9-location.png`,
  },
  'w11169652-dry-heater-j4-location': {
    id: 'w11169652-dry-heater-j4-location',
    caption: 'Dry heating element — J4 (TEST #15)',
    assetPath: `${ASSET_BASE}/w11169652-dry-heater-j4-location.png`,
  },
  'w11169652-dry-ntc-j13-location': {
    id: 'w11169652-dry-ntc-j13-location',
    caption: 'Dry temperature sensor NTC — J13 (TEST #16)',
    assetPath: `${ASSET_BASE}/w11169652-dry-ntc-j13-location.png`,
  },
};

/** Diagram ids to attach for a measurement test-point connector label. */
const CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  RFI: ['w11169652-rfi-filter-figure1'],
  J2: ['w11169652-acu-pinout-figure2'],
  J3: ['w11169652-wash-heater-j3-location', 'w11169652-acu-pinout-figure2'],
  J4: ['w11169652-dry-heater-j4-location', 'w11169652-acu-pinout-figure2'],
  J6: ['w11169652-motor-j6-location', 'w11169652-acu-pinout-figure2'],
  J7: ['w11169652-acu-pinout-figure2'],
  J8: ['w11169652-inlet-valves-strip', 'w11169652-acu-pinout-figure2'],
  J9: ['w11169652-baffle-j9-location', 'w11169652-acu-pinout-figure2'],
  J10: ['w11169652-dosing-pump-strip', 'w11169652-acu-pinout-figure2'],
  J11: ['w11169652-acu-pinout-figure2'],
  J12: ['w11169652-vent-fan-j12-strip', 'w11169652-acu-pinout-figure2'],
  J13: ['w11169652-dry-ntc-j13-location', 'w11169652-acu-pinout-figure2'],
  J14: ['w11169652-water-level-j14', 'w11169652-acu-pinout-figure2'],
  J15: ['w11169652-wash-heater-j3-location', 'w11169652-acu-pinout-figure2'],
  J16: ['w11169652-drum-light-j16-location', 'w11169652-acu-pinout-figure2'],
  J17: ['w11169652-bulk-level-strip', 'w11169652-acu-pinout-figure2'],
  J19: ['w11169652-acu-pinout-figure2'],
  Pump: ['w11169652-dosing-pump-strip'],
  'Vent fan': ['w11169652-vent-fan-j12-strip'],
  Blower: ['w11169652-vent-fan-j12-strip'],
  'Dry NTC': ['w11169652-dry-ntc-j13-location'],
  'Wash NTC': ['w11169652-wash-heater-j3-location'],
  'Level SW': ['w11169652-bulk-level-strip'],
};

const W8178558_ASSET_BASE = '/images/procedures/whirlpool_duet_sport';

/** Cropped OEM figures for W8178558 — generated by crop_w8178558_procedure_figures.py */
export const W8178558_DIAGRAMS: Record<string, ProcedureImage> = {
  'w8178558-ccu-pinout-figure4-5': {
    id: 'w8178558-ccu-pinout-figure4-5',
    caption: 'CCU connector callouts (4-5, manual p. 43)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-ccu-pinout-figure4-5.png`,
  },
  'w8178558-inlet-valves-vch7': {
    id: 'w8178558-inlet-valves-vch7',
    caption: 'Inlet valve solenoids — VCH7 (5-1)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-inlet-valves-vch7.png`,
  },
  'w8178558-pressure-switch-pr6': {
    id: 'w8178558-pressure-switch-pr6',
    caption: 'Pressure switch — PR6 (5-2)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-pressure-switch-pr6.png`,
  },
  'w8178558-dispenser-di6': {
    id: 'w8178558-dispenser-di6',
    caption: 'Detergent dispenser — DI6 (5-4)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-dispenser-di6.png`,
  },
  'w8178558-door-dl3-ds2': {
    id: 'w8178558-door-dl3-ds2',
    caption: 'Door lock DL3 & door switch DS2 (5-5)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-door-dl3-ds2.png`,
  },
  'w8178558-drain-pump-dp2': {
    id: 'w8178558-drain-pump-dp2',
    caption: 'Drain pump — DP2 (5-6)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-drain-pump-dp2.png`,
  },
  'w8178558-heater-th2': {
    id: 'w8178558-heater-th2',
    caption: 'Wash heater HE2 & temp sensor TH2 (5-7)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-heater-th2.png`,
  },
  'w8178558-motor-ms2-interlock': {
    id: 'w8178558-motor-ms2-interlock',
    caption: 'Drive motor MS2 & interlock switch (5-8)',
    assetPath: `${W8178558_ASSET_BASE}/w8178558-motor-ms2-interlock.png`,
  },
};

const W8178558_CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  Motor: ['w8178558-motor-ms2-interlock', 'w8178558-ccu-pinout-figure4-5'],
  MS2: ['w8178558-motor-ms2-interlock', 'w8178558-ccu-pinout-figure4-5'],
  'Drain pump': ['w8178558-drain-pump-dp2', 'w8178558-ccu-pinout-figure4-5'],
  DP2: ['w8178558-drain-pump-dp2', 'w8178558-ccu-pinout-figure4-5'],
  'Inlet valve': ['w8178558-inlet-valves-vch7', 'w8178558-ccu-pinout-figure4-5'],
  VCH7: ['w8178558-inlet-valves-vch7', 'w8178558-ccu-pinout-figure4-5'],
  Heater: ['w8178558-heater-th2', 'w8178558-ccu-pinout-figure4-5'],
  HE2: ['w8178558-heater-th2', 'w8178558-ccu-pinout-figure4-5'],
  'Wash NTC': ['w8178558-heater-th2', 'w8178558-ccu-pinout-figure4-5'],
  TH2: ['w8178558-heater-th2', 'w8178558-ccu-pinout-figure4-5'],
  DL3: ['w8178558-door-dl3-ds2', 'w8178558-ccu-pinout-figure4-5'],
  DS2: ['w8178558-door-dl3-ds2', 'w8178558-ccu-pinout-figure4-5'],
  'Dispenser motor': ['w8178558-dispenser-di6', 'w8178558-ccu-pinout-figure4-5'],
  DI6: ['w8178558-dispenser-di6', 'w8178558-ccu-pinout-figure4-5'],
  PR6: ['w8178558-pressure-switch-pr6', 'w8178558-ccu-pinout-figure4-5'],
};

const W8178559_ASSET_BASE = '/images/procedures/whirlpool_duet_sport_dryer';

export const W8178559_DIAGRAMS: Record<string, ProcedureImage> = {
  'w8178559-mce-pinout-figure17': {
    id: 'w8178559-mce-pinout-figure17',
    caption: 'MCE connectors & pinouts (Figure 17)',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-mce-pinout-figure17.png`,
  },
  'w8178559-motor-figure7-9': {
    id: 'w8178559-motor-figure7-9',
    caption: 'Motor & belt switch — Figures 7–9 (TEST #2)',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-motor-figure7-9.png`,
  },
  'w8178559-heater-figure11': {
    id: 'w8178559-heater-figure11',
    caption: 'Thermal components — Figure 11 (TEST #3)',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-heater-figure11.png`,
  },
  'w8178559-exhaust-thermistor-3a': {
    id: 'w8178559-exhaust-thermistor-3a',
    caption: 'Exhaust thermistor — TEST #3a',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-exhaust-thermistor-3a.png`,
  },
  'w8178559-gas-valve-3d': {
    id: 'w8178559-gas-valve-3d',
    caption: 'Gas valve coils — TEST #3b–3d',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-gas-valve-3d.png`,
  },
  'w8178559-moisture-figure12': {
    id: 'w8178559-moisture-figure12',
    caption: 'Moisture sensor — Figure 12 (TEST #4)',
    assetPath: `${W8178559_ASSET_BASE}/w8178559-moisture-figure12.png`,
  },
};

const W8178559_CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  'Motor main': ['w8178559-motor-figure7-9', 'w8178559-mce-pinout-figure17'],
  'Motor start': ['w8178559-motor-figure7-9', 'w8178559-mce-pinout-figure17'],
  Heater: ['w8178559-heater-figure11', 'w8178559-mce-pinout-figure17'],
  'P14 thermistor': ['w8178559-exhaust-thermistor-3a', 'w8178559-mce-pinout-figure17'],
  Ignitor: ['w8178559-heater-figure11', 'w8178559-gas-valve-3d'],
  'Gas valve': ['w8178559-gas-valve-3d', 'w8178559-mce-pinout-figure17'],
};

const W10864849_ASSET_BASE = '/images/procedures/whirlpool_tl_dd';

/** Cropped OEM figures for W10864849 — generated by crop_w10864849_procedure_figures.py */
export const W10864849_DIAGRAMS: Record<string, ProcedureImage> = {
  'w10864849-acu-pinout-figure1': {
    id: 'w10864849-acu-pinout-figure1',
    caption: 'Main control connectors & pinouts (§3-5)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-acu-pinout-figure1.png`,
  },
  'w10864849-inlet-valves-strip': {
    id: 'w10864849-inlet-valves-strip',
    caption: 'Water inlet valves strip circuit (TEST #2)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-inlet-valves-strip.png`,
  },
  'w10864849-drive-system-figure1': {
    id: 'w10864849-drive-system-figure1',
    caption: 'Drive system — motor & shifter area (TEST #3)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-drive-system-figure1.png`,
  },
  'w10864849-thermistor-strip': {
    id: 'w10864849-thermistor-strip',
    caption: 'Temperature thermistor strip circuit (TEST #5)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-thermistor-strip.png`,
  },
  'w10864849-pumps-strip': {
    id: 'w10864849-pumps-strip',
    caption: 'Drain & recirculation pumps strip circuit (TEST #7)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-pumps-strip.png`,
  },
  'w10864849-lid-lock-schematic': {
    id: 'w10864849-lid-lock-schematic',
    caption: 'Lid lock schematic (TEST #8)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-lid-lock-schematic.png`,
  },
  'w10864849-heater-strip': {
    id: 'w10864849-heater-strip',
    caption: 'Heater element strip circuit (TEST #9)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-heater-strip.png`,
  },
  'w10864849-basket-light-strip': {
    id: 'w10864849-basket-light-strip',
    caption: 'Basket light strip circuit (TEST #11)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-basket-light-strip.png`,
  },
  'w10864849-rex-bulk-dispense': {
    id: 'w10864849-rex-bulk-dispense',
    caption: 'Relay expansion board — bulk dispense (TEST #12)',
    assetPath: `${W10864849_ASSET_BASE}/w10864849-rex-bulk-dispense.png`,
  },
};

const W10864849_PINOUT = 'w10864849-acu-pinout-figure1';

const W10864849_CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  J12: [W10864849_PINOUT],
  J18: [W10864849_PINOUT],
  J2: ['w10864849-inlet-valves-strip', W10864849_PINOUT],
  J1: ['w10864849-drive-system-figure1', W10864849_PINOUT],
  'Drive motor': ['w10864849-drive-system-figure1', W10864849_PINOUT],
  J4: ['w10864849-pumps-strip', W10864849_PINOUT],
  'Drain pump': ['w10864849-pumps-strip', W10864849_PINOUT],
  J6: ['w10864849-lid-lock-schematic', W10864849_PINOUT],
  Heater: ['w10864849-heater-strip', W10864849_PINOUT],
  J19: ['w10864849-basket-light-strip', W10864849_PINOUT],
  'Bulk pump': ['w10864849-rex-bulk-dispense', W10864849_PINOUT],
};

const W11633848_ASSET_BASE = '/images/procedures/whirlpool_dishwasher_acu';

/** Cropped OEM figures for W11633848 — generated by crop_w11633848_procedure_figures.py */
export const W11633848_DIAGRAMS: Record<string, ProcedureImage> = {
  'w11633848-door-switch-strip': {
    id: 'w11633848-door-switch-strip',
    caption: 'Door switch strip circuit (§3-7)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-door-switch-strip.png`,
  },
  'w11633848-fill-valve-strip': {
    id: 'w11633848-fill-valve-strip',
    caption: 'Fill valve strip circuit (§3-8)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-fill-valve-strip.png`,
  },
  'w11633848-heater-strip': {
    id: 'w11633848-heater-strip',
    caption: 'Heater strip circuit (§3-10)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-heater-strip.png`,
  },
  'w11633848-owi-strip': {
    id: 'w11633848-owi-strip',
    caption: 'OWI / water sensing strip circuit (§3-11)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-owi-strip.png`,
  },
  'w11633848-overfill-strip': {
    id: 'w11633848-overfill-strip',
    caption: 'Overfill float switch strip circuit (§3-12)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-overfill-strip.png`,
  },
  'w11633848-wash-motor-strip': {
    id: 'w11633848-wash-motor-strip',
    caption: 'Wash motor strip circuit (§3-15)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-wash-motor-strip.png`,
  },
  'w11633848-drain-motor-strip': {
    id: 'w11633848-drain-motor-strip',
    caption: 'Drain motor strip circuit (§3-16)',
    assetPath: `${W11633848_ASSET_BASE}/w11633848-drain-motor-strip.png`,
  },
};

const W11633848_CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  P9: ['w11633848-door-switch-strip'],
  P6: ['w11633848-fill-valve-strip', 'w11633848-overfill-strip'],
  P4: ['w11633848-heater-strip'],
  P10: ['w11633848-owi-strip'],
  P5: ['w11633848-wash-motor-strip', 'w11633848-drain-motor-strip'],
};

const W10680150_ASSET_BASE = '/images/procedures/whirlpool_ccu_dryer';

/** Cropped OEM figures for W10680150 — generated by crop_w10680150_procedure_figures.py */
export const W10680150_DIAGRAMS: Record<string, ProcedureImage> = {
  'w10680150-ccu-pinout-figure11': {
    id: 'w10680150-ccu-pinout-figure11',
    caption: 'CCU connectors & pinouts (Figure 11, TEST #1)',
    assetPath: `${W10680150_ASSET_BASE}/w10680150-ccu-pinout-figure11.png`,
  },
  'w10680150-motor-figure17-19': {
    id: 'w10680150-motor-figure17-19',
    caption: 'Motor windings & belt switch (Figures 17–19, TEST #3)',
    assetPath: `${W10680150_ASSET_BASE}/w10680150-motor-figure17-19.png`,
  },
  'w10680150-thermal-figure20': {
    id: 'w10680150-thermal-figure20',
    caption: 'Thermal components (Figures 20a/20b, TEST #4)',
    assetPath: `${W10680150_ASSET_BASE}/w10680150-thermal-figure20.png`,
  },
  'w10680150-strip-circuits-figure23': {
    id: 'w10680150-strip-circuits-figure23',
    caption: 'Strip circuits — motor, heater, thermistors (Figure 23)',
    assetPath: `${W10680150_ASSET_BASE}/w10680150-strip-circuits-figure23.png`,
  },
  'w10680150-gas-valve-figure21': {
    id: 'w10680150-gas-valve-figure21',
    caption: 'Gas valve coil resistance (Figure 21, TEST #4d)',
    assetPath: `${W10680150_ASSET_BASE}/w10680150-gas-valve-figure21.png`,
  },
};

const W10680150_PINOUT = 'w10680150-ccu-pinout-figure11';
const W10680150_STRIP = 'w10680150-strip-circuits-figure23';

const W10680150_CONNECTOR_DIAGRAM_IDS: Record<string, string[]> = {
  'CCU motor path': ['w10680150-motor-figure17-19', W10680150_PINOUT, W10680150_STRIP],
  'Motor main': ['w10680150-motor-figure17-19', W10680150_PINOUT, W10680150_STRIP],
  'Motor start': ['w10680150-motor-figure17-19', W10680150_PINOUT, W10680150_STRIP],
  'Heater relays': ['w10680150-thermal-figure20', W10680150_PINOUT, W10680150_STRIP],
  'P14 outlet': [W10680150_PINOUT, W10680150_STRIP],
  'P14 inlet': [W10680150_PINOUT, W10680150_STRIP],
  'Gas valve': ['w10680150-gas-valve-figure21', W10680150_PINOUT, W10680150_STRIP],
  Ignitor: ['w10680150-gas-valve-figure21', 'w10680150-thermal-figure20'],
};

export function resolveDiagramsForConnector(
  connector: string,
  platformId?: string,
): ProcedureImage[] {
  if (platformId === 'whirlpool_duet_sport_dryer') {
    const ids = W8178559_CONNECTOR_DIAGRAM_IDS[connector] || [];
    return ids
      .map((id) => W8178559_DIAGRAMS[id])
      .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
  }

  if (platformId === 'whirlpool_tl_dd') {
    const ids = W10864849_CONNECTOR_DIAGRAM_IDS[connector] || [];
    return ids
      .map((id) => W10864849_DIAGRAMS[id])
      .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
  }

  if (platformId === 'whirlpool_dishwasher_acu') {
    const ids = W11633848_CONNECTOR_DIAGRAM_IDS[connector] || [];
    return ids
      .map((id) => W11633848_DIAGRAMS[id])
      .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
  }

  if (platformId === 'whirlpool_ccu_dryer') {
    const ids = W10680150_CONNECTOR_DIAGRAM_IDS[connector] || [];
    return ids
      .map((id) => W10680150_DIAGRAMS[id])
      .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
  }

  const catalog =
    platformId === 'whirlpool_duet_sport'
      ? W8178558_DIAGRAMS
      : W11169652_DIAGRAMS;
  const connectorMap =
    platformId === 'whirlpool_duet_sport'
      ? W8178558_CONNECTOR_DIAGRAM_IDS
      : CONNECTOR_DIAGRAM_IDS;
  const ids = connectorMap[connector] || [];
  return ids
    .map((id) => catalog[id])
    .filter((item): item is ProcedureImage => Boolean(item?.assetPath));
}

export function serializeProcedureImages(images: ProcedureImage[]): ProcedureImage[] {
  return images.map(({ id, caption, assetPath }) => ({ id, caption, assetPath }));
}
