import type { ComplaintChipDefinition } from '../routing/types';

export const GAS_DRYER_COMPLAINT_CHIPS: ComplaintChipDefinition[] = [
  {
    id: 'no_heat',
    label: 'No Heat / Won\'t Ignite',
    keywords: [
      'no heat',
      'not heating',
      'won\'t ignite',
      'no flame',
      'cold air',
      'f3e1',
      'f3e2',
      'f2e1',
    ],
  },
  {
    id: 'not_drying',
    label: 'Takes Too Long / Damp Clothes',
    keywords: [
      'not drying',
      'damp',
      'wet clothes',
      'too long',
      'hours to dry',
      'f4e3',
      'restricted air flow',
      'restricted airflow',
      'af',
      'f3e6',
      'f3e7',
      'f22',
      'f23',
      'f26',
      'f28',
      'f29',
      'd80',
      'd85',
      'd90',
      'd95',
      'e4',
      'e5',
      'c9',
    ],
  },
  {
    id: 'no_spin',
    label: "Won't Tumble / Drum Not Turning",
    keywords: ['won\'t tumble', 'not turning', 'drum not', 'no spin', 'stuck'],
  },
  {
    id: 'wont_stop_spinning',
    label: "Won't Stop Spinning",
    keywords: ['won\'t stop', 'keeps spinning', 'continuous spin', 'never stops'],
  },
  {
    id: 'gas_smell',
    label: 'Gas Smell / Leak Concern',
    keywords: ['gas smell', 'odor', 'leak', 'mercaptan'],
  },
  {
    id: 'weak_flame',
    label: 'Weak Flame / Goes Out',
    keywords: ['weak flame', 'flame out', 'yellow flame', 'goes out', 'short cycle', 'f4e3', 'restricted air flow'],
  },
  {
    id: 'noisy',
    label: 'Noisy / Thumping',
    keywords: ['noisy', 'squeal', 'thump', 'grinding', 'rattling'],
  },
  {
    id: 'heats_when_shouldnt',
    label: 'Heats on AIR / No-Heat Cycle',
    keywords: [
      'heats on air',
      'heats on fluff',
      'burner on air',
      'won\'t stop heating',
      'stuck heat',
      'f4e1',
    ],
  },
  {
    id: 'error_code',
    label: 'Error Code on Display',
    keywords: ['error', 'fault', 'code', 'f01', 'f22', 'f26', 'f28', 'tc', 'tc5', '9c1', 'dc', 'df', 'hc', 'ac'],
  },
];
