import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { GAS_DRYER_COMPLAINT_CHIPS } from './gasDryerComplaints';
import { gasDryerRoutingConfig } from './gasDryerRouting';

export const gasDryerWizard: WizardDefinition = {
  applianceType: 'gas_dryer',
  templateId: 'gas_dryer',
  title: 'Gas Dryer Diagnostic',
  icon: 'gas_dryer',
  estimatedCompletionMinutes: 16,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: GAS_DRYER_COMPLAINT_CHIPS,
  routing: gasDryerRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'vent', 'gas', 'lint'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'vent', 'igniter', 'valve'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'ignition', 'airflow', 'drum'],
    },
    {
      sectionId: 'gas_ignition',
      stepKey: 'ignition',
      title: 'Gas & Ignition Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['gas', 'igniter', 'valve', 'flame_sensor'],
    },
    {
      sectionId: 'motor_electrical',
      stepKey: 'motor',
      title: 'Motor & Electrical Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['motor', 'voltage', 'fuse', 'board'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
