import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { WASHER_COMPLAINT_CHIPS } from './washerComplaints';
import { washerRoutingConfig } from './washerRouting';

export const washerWizard: WizardDefinition = {
  applianceType: 'washer',
  templateId: 'washer',
  title: 'Washer Diagnostic',
  icon: 'washer',
  estimatedCompletionMinutes: 16,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: WASHER_COMPLAINT_CHIPS,
  routing: washerRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Commonly Missed Items',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'drain', 'level', 'installation'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'suspension', 'leak', 'belt', 'gasket'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'fill', 'drain', 'spin', 'agitate'],
    },
    {
      sectionId: 'electrical_measurements',
      stepKey: 'electrical',
      title: 'Electrical Measurements',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['voltage', 'motor', 'pump', 'valve'],
    },
    {
      sectionId: 'mechanical_controls',
      stepKey: 'mechanical',
      title: 'Mechanical / Control Checks',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['mechanical', 'actuator', 'pressure', 'lock'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
