import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { ELECTRIC_RANGE_COMPLAINT_CHIPS } from './electricRangeComplaints';
import { electricRangeRoutingConfig } from './electricRangeRouting';

export const electricRangeWizard: WizardDefinition = {
  applianceType: 'electric_range',
  templateId: 'electric_range',
  title: 'Electric Range Diagnostic',
  icon: 'electric_range',
  estimatedCompletionMinutes: 18,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: ELECTRIC_RANGE_COMPLAINT_CHIPS,
  routing: electricRangeRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'voltage', 'terminal', 'calibration'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'terminal', 'element', 'door'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'bake', 'broil', 'burners'],
    },
    {
      sectionId: 'terminal_block_readings',
      stepKey: 'terminal',
      title: 'Terminal Block / Supply Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['voltage', 'terminal', 'electrical'],
    },
    {
      sectionId: 'element_sensor_readings',
      stepKey: 'elements',
      title: 'Element & Sensor Readings',
      estimatedMinutes: 4,
      weight: 14,
      optional: true,
      canSkip: true,
      collects: ['element', 'resistance', 'sensor', 'amps'],
    },
    {
      sectionId: 'board_readings',
      stepKey: 'board',
      title: 'Control Board Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['board', 'voltage', 'relay'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
