import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { AIO_LAUNDRY_COMPLAINT_CHIPS } from './aioLaundryComplaints';
import { aioLaundryRoutingConfig } from './aioLaundryRouting';

export const aioLaundryWizard: WizardDefinition = {
  applianceType: 'aio_laundry',
  templateId: 'aio_laundry',
  title: 'AIO Laundry (Heat-Pump Combo) Diagnostic',
  icon: 'aio_laundry',
  estimatedCompletionMinutes: 20,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: AIO_LAUNDRY_COMPLAINT_CHIPS,
  routing: aioLaundryRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'filter', 'vent', 'installation'],
    },
    {
      sectionId: 'wash_functions',
      stepKey: 'wash',
      title: 'Wash Functions',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['washer', 'fill', 'drain', 'spin'],
    },
    {
      sectionId: 'dry_functions',
      stepKey: 'dry',
      title: 'Dry / Heat-Pump Functions',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['dryer', 'heat', 'airflow', 'condensate'],
    },
    {
      sectionId: 'wash_electrical',
      stepKey: 'washElectrical',
      title: 'Wash Electrical Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['washer', 'motor', 'pump', 'pressure'],
    },
    {
      sectionId: 'heat_pump_readings',
      stepKey: 'heatPump',
      title: 'Heat-Pump / Compressor Readings',
      estimatedMinutes: 4,
      weight: 14,
      optional: true,
      canSkip: true,
      collects: ['compressor', 'fan', 'heater', 'refrigerant'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
