"""fix_user_client_relationship

Revision ID: 0a6b389f5f59
Revises: 3468209c0a61
Create Date: 2025-03-17 15:19:25.990194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6b389f5f59'
down_revision: Union[str, None] = '3468209c0a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add nullable columns
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE users SET permissions = '[]'::json WHERE permissions IS NULL")
    op.execute("UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE users SET preferences = '{}'::json WHERE preferences IS NULL")
    
    # Make columns not nullable
    op.alter_column('users', 'permissions',
               existing_type=sa.JSON(),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
    
    # Other alterations
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'manager', 'technician', 'client', name='user_role_enum'),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    
    op.drop_index('ix_users_auth_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['auth_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_auth_id', 'users', ['auth_id'], unique=False)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('admin', 'manager', 'technician', 'client', name='user_role_enum'),
               nullable=True)
    op.alter_column('users', 'auth_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
