"""Create appointment_services_association table

Revision ID: 1cd2e466cacd
Revises: fc10c1e3877a
Create Date: 2025-05-16 23:19:22.188667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd2e466cacd'
down_revision: Union[str, None] = 'fc10c1e3877a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('appointment_services_association',
    # sa.Column('appointment_id', sa.UUID(), nullable=False),
    # sa.Column('service_id', sa.UUID(), nullable=False),
    # sa.ForeignKeyConstraint(['appointment_id'], ['work_order_appointments.id'], ),
    # sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    # sa.PrimaryKeyConstraint('appointment_id', 'service_id')
    # )
    pass # Add pass because all operations are commented out
    # op.drop_table('work_order_services')
    # op.drop_table('audit_log')
    # with op.batch_alter_table('invoice_items', schema=None) as batch_op:
    #     batch_op.alter_column('unit_price',
    #            existing_type=sa.NUMERIC(precision=19, scale=4),
    #            type_=sa.Float(),
    #            existing_nullable=False)
    #     batch_op.alter_column('total',
    #            existing_type=sa.NUMERIC(precision=19, scale=4),
    #            type_=sa.Float(),
    #            existing_nullable=False)
    #     batch_op.drop_constraint('invoice_items_work_order_service_id_fkey', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'work_order_service', ['work_order_service_id'], ['id'])

    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('draft', 'sent', 'paid', 'partially_paid', 'overdue', 'cancelled', name='invoice_status_enum'),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.alter_column('discount_amount',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            server_default=None,
    #            existing_nullable=False)
    #     batch_op.alter_column('total_amount',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            server_default=None,
    #            existing_nullable=False)
    #     batch_op.drop_index('idx_invoices_client_status')

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_column('delivered_at')

    # with op.batch_alter_table('payments', schema=None) as batch_op:
    #     batch_op.alter_column('amount',
    #            existing_type=sa.NUMERIC(precision=19, scale=4),
    #            type_=sa.Float(),
    #            existing_nullable=False)
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('success', 'pending', 'failed', 'refunded', name='payment_status_enum'),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.drop_index('idx_payments_invoice_status')

    # with op.batch_alter_table('quotes', schema=None) as batch_op:
    #     batch_op.alter_column('status',
    #            existing_type=sa.VARCHAR(length=20),
    #            server_default=None,
    #            nullable=True)

    # with op.batch_alter_table('service_bundles', schema=None) as batch_op:
    #     batch_op.drop_index('ix_service_bundles_bundle_service_id')
    #     batch_op.drop_index('ix_service_bundles_included_service_id')

    # with op.batch_alter_table('service_surcharges', schema=None) as batch_op:
    #     batch_op.drop_index('ix_service_surcharges_surcharge_type')

    # with op.batch_alter_table('services', schema=None) as batch_op:
    #     batch_op.alter_column('unit',
    #            existing_type=sa.VARCHAR(length=50),
    #            server_default=None,
    #            existing_nullable=True)
    #     batch_op.alter_column('equipment_type',
    #            existing_type=postgresql.ENUM('washer', 'dryer', 'stacked_laundry', 'aio_laundry', 'refrigerator', 'dishwasher', 'range', 'wall_oven', 'tv', 'network', 'other', name='equipment_type'),
    #            type_=sa.Enum('WASHER', 'DRYER', 'STACKED_LAUNDRY', 'AIO_LAUNDRY', 'REFRIGERATOR', 'DISHWASHER', 'RANGE', 'WALL_OVEN', 'TV', 'NETWORK', 'OTHER', name='equipmenttype'),
    #            existing_nullable=True)
    #     batch_op.alter_column('skill_level',
    #            existing_type=postgresql.ENUM('basic', 'intermediate', 'advanced', name='serviceskill_level'),
    #            type_=sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', name='serviceskilllevel'),
    #            existing_nullable=True)
    #     batch_op.alter_column('is_bundle',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.alter_column('is_custom_price',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.alter_column('requires_diagnostic',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            nullable=True)

    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)
    #     batch_op.alter_column('category',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)

    # with op.batch_alter_table('technician_skills', schema=None) as batch_op:
    #     batch_op.alter_column('proficiency_level',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level_enum'),
    #            nullable=False)
    #     batch_op.alter_column('is_primary',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.drop_constraint('technician_skills_skill_id_fkey', type_='foreignkey')
    #     batch_op.drop_constraint('technician_skills_technician_id_fkey', type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'technicians', ['technician_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('roles',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            server_default=None,
    #            existing_nullable=False)

    # with op.batch_alter_table('work_order_appointments', schema=None) as batch_op:
    #     batch_op.drop_index('idx_work_order_appointments_scheduled_start')
    #     batch_op.drop_index('idx_work_order_appointments_status')
    #     batch_op.drop_index('idx_work_order_appointments_technician_id')
    #     batch_op.drop_index('idx_work_order_appointments_work_order_id')
    #     batch_op.drop_column('time_window')

    # with op.batch_alter_table('work_order_items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.NUMERIC(precision=19, scale=4),
    #            type_=sa.Float(),
    #            existing_nullable=False)

    # with op.batch_alter_table('work_order_service', schema=None) as batch_op:
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(length=255),
    #            server_default=None,
    #            existing_nullable=False)
    #     batch_op.alter_column('quantity',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            server_default=None,
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    #     batch_op.alter_column('unit_price',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=None,
    #            existing_nullable=False)
    #     batch_op.create_index(batch_op.f('ix_work_order_service_service_id'), ['service_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_work_order_service_work_order_id'), ['work_order_id'], unique=False)
    #     batch_op.drop_column('price')

    # with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
    #     batch_op.drop_constraint('fk_work_order_status_history_changed_by', type_='foreignkey')

    # with op.batch_alter_table('work_orders', schema=None) as batch_op:
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('pending', 'scheduled', 'in_progress', 'on_hold', 'completed', 'cancelled', 'parts_on_order', 'reschedule', 'need_to_contact', 'redo', name='work_order_status_enum'),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.alter_column('is_wall_mounted',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            nullable=True)
    #     batch_op.alter_column('invoice_subtotal',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=None,
    #            existing_nullable=True)
    #     batch_op.alter_column('invoice_tax',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=None,
    #            existing_nullable=True)
    #     batch_op.alter_column('invoice_total',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=None,
    #            existing_nullable=True)
    #     batch_op.drop_index('idx_work_order_assigned_status')
    #     batch_op.drop_index('idx_work_orders_client_status')
    #     batch_op.drop_index('idx_work_orders_fulltext', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_services_association') # This should be active
    # with op.batch_alter_table('work_orders', schema=None) as batch_op:
    #     batch_op.create_index('idx_work_orders_fulltext', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    #     batch_op.create_index('idx_work_orders_client_status', ['client_id', 'status'], unique=False)
    #     batch_op.create_index('idx_work_order_assigned_status', ['assigned_technician_id', 'status'], unique=False)
    #     batch_op.alter_column('invoice_total',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=sa.text('0.00'),
    #            existing_nullable=True)
    #     batch_op.alter_column('invoice_tax',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=sa.text('0.00'),
    #            existing_nullable=True)
    #     batch_op.alter_column('invoice_subtotal',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=sa.text('0.00'),
    #            existing_nullable=True)
    #     batch_op.alter_column('is_wall_mounted',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text('false'),
    #            nullable=False)
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('pending', 'scheduled', 'in_progress', 'on_hold', 'completed', 'cancelled', 'parts_on_order', 'reschedule', 'need_to_contact', 'redo', name='work_order_status_enum'),
    #            server_default=sa.text("'pending'::work_order_status_enum"),
    #            nullable=False)

    # with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
    #     batch_op.create_foreign_key('fk_work_order_status_history_changed_by', 'users', ['changed_by'], ['id'], ondelete='SET NULL')

    # with op.batch_alter_table('work_order_service', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    #     batch_op.drop_index(batch_op.f('ix_work_order_service_work_order_id'))
    #     batch_op.drop_index(batch_op.f('ix_work_order_service_service_id'))
    #     batch_op.alter_column('unit_price',
    #            existing_type=sa.NUMERIC(precision=10, scale=2),
    #            server_default=sa.text('0.00'),
    #            existing_nullable=False)
    #     batch_op.alter_column('quantity',
    #            existing_type=sa.Integer(),
    #            server_default=sa.text('1'),
    #            type_=sa.DOUBLE_PRECISION(precision=53),
    #            existing_nullable=False)
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(length=255),
    #            server_default=sa.text("'Unnamed Service'::character varying"),
    #            existing_nullable=False)

    # with op.batch_alter_table('work_order_items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.Float(),
    #            type_=sa.NUMERIC(precision=19, scale=4),
    #            existing_nullable=False)

    # with op.batch_alter_table('work_order_appointments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('time_window', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    #     batch_op.create_index('idx_work_order_appointments_work_order_id', ['work_order_id'], unique=False)
    #     batch_op.create_index('idx_work_order_appointments_technician_id', ['assigned_technician_id'], unique=False)
    #     batch_op.create_index('idx_work_order_appointments_status', ['status'], unique=False)
    #     batch_op.create_index('idx_work_order_appointments_scheduled_start', ['scheduled_start'], unique=False)

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.alter_column('roles',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            server_default=sa.text("'[]'::json"),
    #            existing_nullable=False)

    # with op.batch_alter_table('technician_skills', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key('technician_skills_technician_id_fkey', 'technicians', ['technician_id'], ['id'])
    #     batch_op.create_foreign_key('technician_skills_skill_id_fkey', 'skills', ['skill_id'], ['id'])
    #     batch_op.alter_column('is_primary',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text('false'),
    #            nullable=False)
    #     batch_op.alter_column('proficiency_level',
    #            existing_type=sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level_enum'),
    #            type_=sa.VARCHAR(length=20),
    #            nullable=True)

    # with op.batch_alter_table('skills', schema=None) as batch_op:
    #     batch_op.alter_column('category',
    #            existing_type=sa.String(length=100),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    #     batch_op.alter_column('name',
    #            existing_type=sa.String(length=255),
    #            type_=sa.VARCHAR(length=100),
    #            existing_nullable=False)

    # with op.batch_alter_table('services', schema=None) as batch_op:
    #     batch_op.alter_column('requires_diagnostic',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text('false'),
    #            nullable=False)
    #     batch_op.alter_column('is_custom_price',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text('false'),
    #            nullable=False)
    #     batch_op.alter_column('is_bundle',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text('false'),
    #            nullable=False)
    #     batch_op.alter_column('skill_level',
    #            existing_type=sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', name='serviceskilllevel'),
    #            type_=postgresql.ENUM('basic', 'intermediate', 'advanced', name='serviceskill_level'),
    #            existing_nullable=True)
    #     batch_op.alter_column('equipment_type',
    #            existing_type=sa.Enum('WASHER', 'DRYER', 'STACKED_LAUNDRY', 'AIO_LAUNDRY', 'REFRIGERATOR', 'DISHWASHER', 'RANGE', 'WALL_OVEN', 'TV', 'NETWORK', 'OTHER', name='equipmenttype'),
    #            type_=postgresql.ENUM('washer', 'dryer', 'stacked_laundry', 'aio_laundry', 'refrigerator', 'dishwasher', 'range', 'wall_oven', 'tv', 'network', 'other', name='equipment_type'),
    #            existing_nullable=True)
    #     batch_op.alter_column('unit',
    #            existing_type=sa.VARCHAR(length=50),
    #            server_default=sa.text("'item'::character varying"),
    #            existing_nullable=True)

    # with op.batch_alter_table('service_surcharges', schema=None) as batch_op:
    #     batch_op.create_index('ix_service_surcharges_surcharge_type', ['surcharge_type'], unique=False)

    # with op.batch_alter_table('service_bundles', schema=None) as batch_op:
    #     batch_op.create_index('ix_service_bundles_included_service_id', ['included_service_id'], unique=False)
    #     batch_op.create_index('ix_service_bundles_bundle_service_id', ['bundle_service_id'], unique=False)

    # with op.batch_alter_table('quotes', schema=None) as batch_op:
    #     batch_op.alter_column('status',
    #            existing_type=sa.VARCHAR(length=20),
    #            server_default=sa.text("'draft'::character varying"),
    #            nullable=False)

    # with op.batch_alter_table('payments', schema=None) as batch_op:
    #     batch_op.create_index('idx_payments_invoice_status', ['invoice_id', 'status'], unique=False)
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('success', 'pending', 'failed', 'refunded', name='payment_status_enum'),
    #            server_default=sa.text("'pending'::payment_status_enum"),
    #            nullable=False)
    #     batch_op.alter_column('amount',
    #            existing_type=sa.Float(),
    #            type_=sa.NUMERIC(precision=19, scale=4),
    #            existing_nullable=False)

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.create_index('idx_invoices_client_status', ['client_id', 'status'], unique=False)
    #     batch_op.alter_column('total_amount',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            server_default=sa.text('0.0'),
    #            existing_nullable=False)
    #     batch_op.alter_column('discount_amount',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            server_default=sa.text('0.0'),
    #            existing_nullable=False)
    #     batch_op.alter_column('status',
    #            existing_type=postgresql.ENUM('draft', 'sent', 'paid', 'partially_paid', 'overdue', 'cancelled', name='invoice_status_enum'),
    #            server_default=sa.text("'draft'::invoice_status_enum"),
    #            nullable=False)

    # with op.batch_alter_table('invoice_items', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key('invoice_items_work_order_service_id_fkey', 'work_order_services', ['work_order_service_id'], ['id'])
    #     batch_op.alter_column('total',
    #            existing_type=sa.Float(),
    #            type_=sa.NUMERIC(precision=19, scale=4),
    #            existing_nullable=False)
    #     batch_op.alter_column('unit_price',
    #            existing_type=sa.Float(),
    #            type_=sa.NUMERIC(precision=19, scale=4),
    #            existing_nullable=False)

    # op.create_table('audit_log',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_log_user_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    # )
    # op.create_table('work_order_services',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('work_order_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='work_order_services_service_id_fkey'),
    # sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name='work_order_services_work_order_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='work_order_services_pkey')
    # )
    # ### end Alembic commands ###
