"""add_time_window_to_appointments

Revision ID: ad046c98abc1
Revises: ec477ea34833
Create Date: 2025-04-15 22:42:15.750268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad046c98abc1'
down_revision: Union[str, None] = 'ec477ea34833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add time_window column to work_order_appointments
    op.add_column('work_order_appointments', sa.Column('time_window', sa.String(length=20), nullable=True))
    
    # Create enum type for time window values
    op.create_check_constraint(
        'check_time_window_values',
        'work_order_appointments',
        "time_window IN ('morning', 'afternoon')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove check constraint
    op.drop_constraint('check_time_window_values', 'work_order_appointments', type_='check')
    
    # Remove time_window column
    op.drop_column('work_order_appointments', 'time_window')
    # ### end Alembic commands ###
