"""manual_invoice_schema_changes

Revision ID: b1106f7fef34
Revises: ad046c98abc1
Create Date: 2025-05-15 23:06:38.029087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1106f7fef34'
down_revision: Union[str, None] = 'ad046c98abc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add columns to work_orders table
    op.add_column('work_orders', sa.Column('invoice_subtotal', sa.Numeric(precision=10, scale=2), nullable=True, server_default=sa.text('0.00')))
    op.add_column('work_orders', sa.Column('invoice_tax', sa.Numeric(precision=10, scale=2), nullable=True, server_default=sa.text('0.00')))
    op.add_column('work_orders', sa.Column('invoice_total', sa.Numeric(precision=10, scale=2), nullable=True, server_default=sa.text('0.00')))

    # Add columns to work_order_service table
    op.add_column('work_order_service', sa.Column('name', sa.String(length=255), nullable=False, server_default='Unnamed Service')) # Added server_default temporarily if old rows exist
    op.add_column('work_order_service', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.00'))) # Added server_default temporarily
    # op.add_column('work_order_service', sa.Column('notes', sa.Text(), nullable=True)) # This line will be commented out/removed

    # Adjustments for existing 'quantity' column in work_order_service if necessary
    # Assuming 'quantity' already exists as per user, this is an example if it needed alteration:
    # op.alter_column('work_order_service', 'quantity',
    #               existing_type=sa.FLOAT(), # Replace with actual existing type if different
    #               type_=sa.Integer(),
    #               nullable=False,
    #               server_default=sa.text('1'),
    #               postgresql_using='quantity::integer' # If type conversion is needed
    #              )
    # If quantity is already Integer and NOT NULL, ensure server_default is applied if it wasn't or was different.
    # Forcing a server_default on an existing column might require more specific handling if values already exist.
    # If it's truly only the default we want to ensure, and the column is otherwise fine:
    op.alter_column('work_order_service', 'quantity', server_default=sa.text('1'))
    
    # Ensure ForeignKeys and Indexes for work_order_service (idempotent checks)
    # These might already exist from a previous migration but good to ensure for clarity.
    # Alembic's autogenerate usually handles these well if it creates the table initially.
    # If 'work_order_service' was created without these, they would be added.
    # For an existing table, ensure these don't cause errors if already present.
    # Typically, op.create_foreign_key and op.create_index have 'if_not_exists' behavior or equivalent
    # or one would check before creating.
    # op.create_index(op.f('ix_work_order_service_service_id'), 'work_order_service', ['service_id'], unique=False) # if not already indexed
    # op.create_index(op.f('ix_work_order_service_work_order_id'), 'work_order_service', ['work_order_id'], unique=False) # if not already indexed

    # If 'name' and 'unit_price' were added to non-empty table and are NOT NULL without a Python-side default during ORM use,
    # existing rows would need a value. Added server_default temporarily.
    # If you have a proper data migration strategy for existing rows, server_default can be removed post-update.
    # If the table is new or empty, server_default on nullable=False is less critical during add_column.

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from work_order_service table
    # Consider order if there are dependencies or if server_default needs to be dropped first for some DBs
    # op.drop_column('work_order_service', 'notes') # This line will be commented out/removed
    op.drop_column('work_order_service', 'unit_price')
    op.drop_column('work_order_service', 'name')
    
    # Revert 'quantity' alterations on work_order_service if any specific changes were made in upgrade
    # This is an example, make it match the upgrade's alteration precisely
    # op.alter_column('work_order_service', 'quantity', server_default=None) # Or original server_default if it had one

    # Remove columns from work_orders table
    op.drop_column('work_orders', 'invoice_total')
    op.drop_column('work_orders', 'invoice_tax')
    op.drop_column('work_orders', 'invoice_subtotal')

    # ### end Alembic commands ###
