"""Add skills and technician_skills tables

Revision ID: cffe74267cd7
Revises: 448252fbd0e4
Create Date: 2025-03-31 17:09:21.265245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cffe74267cd7'
down_revision: Union[str, None] = '448252fbd0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create skills table first
    op.create_table('skills',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # Create technician_skills table
    op.create_table('technician_skills',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('technician_id', sa.UUID(), nullable=False),
        sa.Column('skill_id', sa.UUID(), nullable=False),
        sa.Column('proficiency_level', sa.String(length=20), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
        sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Drop unused tables
    op.drop_table('settings')
    op.drop_index('ix_system_logs_event_type', table_name='system_logs')
    op.drop_index('ix_system_logs_timestamp', table_name='system_logs')
    op.drop_table('system_logs')

    # Add new columns to invoices
    op.add_column('invoices', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('total_amount', sa.Float(), nullable=False, server_default='0'))
    op.drop_column('invoices', 'total')
    op.drop_column('invoices', 'discount')

    # Update services table
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('services', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'hour'::character varying"))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('services', 'requires_technician')
    op.drop_column('services', 'duration')
    op.drop_column('services', 'requires_parts')
    op.drop_column('services', 'meta_data')

    # Update users table
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint('users_auth_id_key', 'users', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Add description to work_order_items
    op.add_column('work_order_items', sa.Column('description', sa.String(length=255), nullable=False, server_default=''))
    op.alter_column('work_order_items', 'description',
               existing_type=sa.String(length=255),
               nullable=False,
               server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove description from work_order_items
    op.drop_column('work_order_items', 'description')

    # Restore users table constraints
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('users_auth_id_key', 'users', ['auth_id'])
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # Restore services table columns
    op.add_column('services', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('requires_parts', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('requires_technician', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('services', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'hour'::character varying"))
    op.alter_column('services', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # Restore invoice columns
    op.add_column('invoices', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'discount_amount')

    # Restore system tables
    op.create_table('system_logs',
        sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='system_logs_pkey')
    )
    op.create_index('ix_system_logs_timestamp', 'system_logs', ['timestamp'], unique=False)
    op.create_index('ix_system_logs_event_type', 'system_logs', ['event_type'], unique=False)

    op.create_table('settings',
        sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('key', name='settings_pkey')
    )

    # Drop technician_skills table
    op.drop_table('technician_skills')

    # Drop skills table
    op.drop_table('skills')
    # ### end Alembic commands ###
