"""add_travel_time_fields_to_appointments

Revision ID: ec477ea34833
Revises: 5ead1a9d5ab0
Create Date: 2025-04-15 17:00:15.498558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec477ea34833'
down_revision: Union[str, None] = '5ead1a9d5ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_appointments', sa.Column('travel_time_before', sa.Integer(), nullable=True))
    op.add_column('work_order_appointments', sa.Column('travel_time_after', sa.Integer(), nullable=True))
    op.add_column('work_order_appointments', sa.Column('travel_distance_before', sa.Integer(), nullable=True))
    op.add_column('work_order_appointments', sa.Column('travel_distance_after', sa.Integer(), nullable=True))
    op.add_column('work_order_appointments', sa.Column('is_forced_schedule', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_appointments', 'is_forced_schedule')
    op.drop_column('work_order_appointments', 'travel_distance_after')
    op.drop_column('work_order_appointments', 'travel_distance_before')
    op.drop_column('work_order_appointments', 'travel_time_after')
    op.drop_column('work_order_appointments', 'travel_time_before')
    # ### end Alembic commands ###
