import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { REFRIGERATOR_COMPLAINT_CHIPS } from './refrigeratorComplaints';
import { refrigeratorRoutingConfig } from './refrigeratorRouting';

/**
 * Reference WizardDefinition — rich metadata for DMA / analytics (Phase 6).
 * Field definitions remain in diagnosticTemplates.js (refrigerator template).
 */
export const refrigeratorWizard: WizardDefinition = {
  applianceType: 'refrigerator',
  templateId: 'refrigerator',
  title: 'Refrigerator Diagnostic',
  icon: 'refrigerator',
  estimatedCompletionMinutes: 20,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: REFRIGERATOR_COMPLAINT_CHIPS,
  routing: refrigeratorRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      description: 'Document complaint, duration, and error codes.',
      icon: 'complaint',
      estimatedMinutes: 2,
      required: false,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes', 'duration'],
    },
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      description: 'Quick checks often overlooked on service calls.',
      icon: 'checklist',
      estimatedMinutes: 2,
      required: false,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'visual', 'installation', 'ventilation'],
    },
    {
      sectionId: 'temperature_checks',
      stepKey: 'temperature',
      title: 'Temperature Checks',
      description: 'Compartment and ambient temperature readings.',
      icon: 'thermometer',
      estimatedMinutes: 2,
      required: false,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['temperature', 'fresh_food', 'freezer', 'ambient'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      description: 'Inspect cabinet, gaskets, condenser, and frost pattern.',
      icon: 'visual',
      estimatedMinutes: 3,
      required: false,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['visual', 'gasket', 'cabinet', 'doors', 'condenser', 'evaporator_frost'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      description: 'Verify compressor, fans, defrost, and dispenser operation.',
      icon: 'functional',
      estimatedMinutes: 3,
      required: false,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'compressor', 'fans', 'defrost', 'ice_maker', 'dispenser'],
    },
    {
      sectionId: 'compressor_sealed_system',
      stepKey: 'sealedSystem',
      title: 'Compressor & Sealed System Readings',
      description: 'Compressor electrical and sealed-system measurements.',
      icon: 'compressor',
      estimatedMinutes: 4,
      required: false,
      weight: 14,
      optional: true,
      canSkip: true,
      collects: ['amps', 'voltage', 'resistance', 'compressor', 'refrigerant', 'start_device'],
    },
    {
      sectionId: 'defrost_circuit',
      stepKey: 'defrost',
      title: 'Defrost Circuit Readings',
      description: 'Defrost heater, thermostat, fuse, and thermistor.',
      icon: 'defrost',
      estimatedMinutes: 2,
      required: false,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['defrost', 'resistance', 'thermistor', 'fuse'],
    },
    {
      sectionId: 'fans_and_electrical',
      stepKey: 'fans',
      title: 'Fans & Electrical Readings',
      description: 'Fan amps, supply voltage, and thermistors.',
      icon: 'electrical',
      estimatedMinutes: 3,
      required: false,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['fans', 'amps', 'voltage', 'thermistor', 'control_board'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      description: 'Root cause and recommended repair.',
      icon: 'diagnosis',
      estimatedMinutes: 3,
      required: false,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
