"""Default DMA repair tag vocabulary."""

DEFAULT_DMA_TAGS: list[tuple[str, str]] = [
    ("drain", "Drain"),
    ("drain_pump", "Drain pump"),
    ("compressor", "Compressor"),
    ("frost", "Frost / defrost"),
    ("evap_fan", "Evap fan"),
    ("control_board", "Control board"),
    ("pressure_hose", "Pressure hose"),
    ("thermistor", "Thermistor"),
    ("inlet_valve", "Inlet valve"),
    ("door_latch", "Door latch"),
    ("heating_element", "Heating element"),
    ("igniter", "Igniter"),
    ("belt", "Belt"),
    ("motor", "Motor"),
    ("inverter_board", "Inverter board"),
    ("leak", "Leak"),
    ("wiring", "Wiring / harness"),
    ("capacitor", "Capacitor"),
    ("fan_motor", "Fan motor"),
    ("ice_maker", "Ice maker"),
    ("vent", "Vent / airflow"),
    ("sensor", "Sensor"),
    ("pump", "Pump"),
    ("filter", "Filter"),
    ("detergent", "Detergent / suds"),
]
