"""Constants for standalone Solomon diagnostics and DMA field records."""

DMA_CONTEXT_TECH = "tech"
DMA_CONTEXT_TRAINING = "training"
DMA_CONTEXT_DIY = "diy"
DMA_CONTEXTS = frozenset({DMA_CONTEXT_TECH, DMA_CONTEXT_TRAINING, DMA_CONTEXT_DIY})

DMA_VISIBILITY_PRIVATE = "private"
DMA_VISIBILITY_ORG = "org"
DMA_VISIBILITY_TRAINING_CORPUS = "training_corpus"
DMA_VISIBILITY_PUBLIC = "public"
DMA_VISIBILITIES = frozenset({
    DMA_VISIBILITY_PRIVATE,
    DMA_VISIBILITY_ORG,
    DMA_VISIBILITY_TRAINING_CORPUS,
    DMA_VISIBILITY_PUBLIC,
})

DMA_MODERATION_PENDING = "pending"
DMA_MODERATION_APPROVED = "approved"
DMA_MODERATION_REJECTED = "rejected"
DMA_MODERATION_STATUSES = frozenset({
    DMA_MODERATION_PENDING,
    DMA_MODERATION_APPROVED,
    DMA_MODERATION_REJECTED,
})

POOL_VISIBILITIES = frozenset({
    DMA_VISIBILITY_TRAINING_CORPUS,
    DMA_VISIBILITY_PUBLIC,
})

DMA_DIAGNOSTIC_IN_PROGRESS = "in_progress"
DMA_DIAGNOSTIC_COMPLETED = "completed"
DMA_DIAGNOSTIC_ABANDONED = "abandoned"
DMA_DIAGNOSTIC_STATUSES = frozenset({
    DMA_DIAGNOSTIC_IN_PROGRESS,
    DMA_DIAGNOSTIC_COMPLETED,
    DMA_DIAGNOSTIC_ABANDONED,
})

OUTCOME_CONFIDENCE_CONFIRMED = "confirmed"
OUTCOME_CONFIDENCE_LIKELY = "likely"
OUTCOME_CONFIDENCE_UNCONFIRMED = "unconfirmed"
OUTCOME_CONFIDENCE_INCORRECT = "incorrect"
OUTCOME_CONFIDENCE_VALUES = frozenset({
    OUTCOME_CONFIDENCE_CONFIRMED,
    OUTCOME_CONFIDENCE_LIKELY,
    OUTCOME_CONFIDENCE_UNCONFIRMED,
    OUTCOME_CONFIDENCE_INCORRECT,
})
