import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { STACKED_LAUNDRY_COMPLAINT_CHIPS } from './stackedLaundryComplaints';
import { stackedLaundryRoutingConfig } from './stackedLaundryRouting';

export const stackedLaundryWizard: WizardDefinition = {
  applianceType: 'stacked_laundry',
  templateId: 'stacked_laundry',
  title: 'Laundry Center / Stacked Unit Diagnostic',
  icon: 'stacked_laundry',
  estimatedCompletionMinutes: 18,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: STACKED_LAUNDRY_COMPLAINT_CHIPS,
  routing: stackedLaundryRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Pre-Checks',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'vent', 'installation', 'power'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Client Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'washer_section',
      stepKey: 'washer',
      title: 'Washer Section',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['washer', 'fill', 'drain', 'spin'],
    },
    {
      sectionId: 'dryer_section',
      stepKey: 'dryer',
      title: 'Dryer Section',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['dryer', 'heat', 'airflow', 'drum'],
    },
    {
      sectionId: 'washer_measurements',
      stepKey: 'washerElectrical',
      title: 'Washer Electrical Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['washer', 'motor', 'pump', 'pressure'],
    },
    {
      sectionId: 'dryer_measurements',
      stepKey: 'dryerElectrical',
      title: 'Dryer Heat / Motor Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['dryer', 'heat', 'motor', 'fuse'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
