import type { WizardDefinition } from '../types';
import { DIAGNOSTIC_REVIEW_STEP_ID } from '../shared/createWizardDefinitionFromTemplate';
import { MICROWAVE_COMPLAINT_CHIPS } from './microwaveComplaints';
import { microwaveRoutingConfig } from './microwaveRouting';

export const microwaveWizard: WizardDefinition = {
  applianceType: 'microwave',
  templateId: 'microwave',
  title: 'Microwave Diagnostic',
  icon: 'microwave',
  estimatedCompletionMinutes: 14,
  version: '1.0.0',
  featureFlags: {},
  symptomFlows: [],
  complaintChips: MICROWAVE_COMPLAINT_CHIPS,
  routing: microwaveRoutingConfig,
  defaultSteps: [
    {
      sectionId: 'commonly_missed',
      stepKey: 'commonly_missed',
      title: 'Commonly Missed Items',
      estimatedMinutes: 2,
      weight: 6,
      optional: true,
      canSkip: true,
      collects: ['checklist', 'door', 'installation', 'ventilation'],
    },
    {
      sectionId: 'customer_complaint',
      stepKey: 'complaint',
      title: 'Customer Complaint',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['complaint', 'symptoms', 'error_codes'],
    },
    {
      sectionId: 'visual_inspection',
      stepKey: 'visual',
      title: 'Visual Inspection',
      estimatedMinutes: 2,
      weight: 8,
      optional: true,
      canSkip: true,
      collects: ['visual', 'door', 'waveguide', 'turntable'],
    },
    {
      sectionId: 'functional_checks',
      stepKey: 'functional',
      title: 'Functional Checks',
      estimatedMinutes: 3,
      weight: 10,
      optional: true,
      canSkip: true,
      collects: ['functional', 'heat', 'turntable', 'fan'],
    },
    {
      sectionId: 'door_safety',
      stepKey: 'door',
      title: 'Door & Safety Switch Readings',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['door', 'safety', 'fuse', 'switch'],
    },
    {
      sectionId: 'electrical_hv',
      stepKey: 'hv',
      title: 'Electrical / HV Circuit',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['hv', 'magnetron', 'capacitor', 'diode'],
    },
    {
      sectionId: 'diagnosis',
      stepKey: 'diagnosis',
      title: 'Diagnosis',
      estimatedMinutes: 3,
      weight: 12,
      optional: true,
      canSkip: true,
      collects: ['diagnosis', 'root_cause', 'repair_plan'],
    },
  ],
  reviewStep: {
    id: DIAGNOSTIC_REVIEW_STEP_ID,
    title: 'Review & Save',
    description: 'Confirm diagnostic entries before saving the note.',
    estimatedMinutes: 1,
    weight: 5,
  },
  completionBehavior: { type: 'save_diagnostic_note' },
};
